import React, { createContext, useContext, useState, ReactNode } from 'react';

interface LanguageContextType {
  language: string;
  setLanguage: (lang: string) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

interface LanguageProviderProps {
  children: ReactNode;
}

export const LanguageProvider: React.FC<LanguageProviderProps> = ({ children }) => {
  const [language, setLanguage] = useState<string>(() => {
    // Get language from localStorage or default to 'es'
    if (typeof window !== 'undefined') {
      const savedLanguage = localStorage.getItem('language');
      return savedLanguage || 'es';
    }
    return 'es';
  });

  const translations: Record<string, Record<string, string>> = {
    es: {
      'welcome.title': 'Bienvenido a JoySense Dashboard',
      'welcome.subtitle': 'Sistema de Monitoreo Inteligente',
      'dashboard.title': 'Dashboard',
      'reports.title': 'Reportes',
      'alerts.title': 'Alertas',
      'messages.title': 'Mensajes',
      'login.title': 'Iniciar Sesión',
      'login.subtitle': 'Accede a tu cuenta',
      'login.email': 'Correo Electrónico',
      'login.password': 'Contraseña',
      'login.button': 'Iniciar Sesión',
      'login.error': 'Credenciales inválidas',
      'logout.button': 'Cerrar Sesión',
      'loading': 'Cargando...',
      'error': 'Error',
      'success': 'Éxito',
      'warning': 'Advertencia',
      'info': 'Información',
      'save': 'Guardar',
      'cancel': 'Cancelar',
      'delete': 'Eliminar',
      'edit': 'Editar',
      'create': 'Crear',
      'update': 'Actualizar',
      'search': 'Buscar',
      'filter': 'Filtrar',
      'reset': 'Restablecer',
      'confirm': 'Confirmar',
      'yes': 'Sí',
      'no': 'No',
      'close': 'Cerrar',
      'back': 'Volver',
      'next': 'Siguiente',
      'previous': 'Anterior',
      'select': 'Seleccionar',
      'all': 'Todos',
      'none': 'Ninguno',
      'status': 'Estado',
      'active': 'Activo',
      'inactive': 'Inactivo',
      'enabled': 'Habilitado',
      'disabled': 'Deshabilitado',
      'country': 'País',
      'company': 'Empresa',
      'fund': 'Fundo',
      'location': 'Ubicación',
      'entity': 'Entidad',
      'node': 'Nodo',
      'sensor': 'Sensor',
      'metric': 'Métrica',
      'type': 'Tipo',
      'measurement': 'Medición',
      'threshold': 'Umbral',
      'alert': 'Alerta',
      'user': 'Usuario',
      'medium': 'Medio',
      'contact': 'Contacto',
      'localization': 'Localización',
      'sensor_metric': 'Métrica Sensor',
      'threshold_profile': 'Perfil Umbral',
      'audit_log_threshold': 'Audit Log Umbral',
      'criticality': 'Criticidad',
      'name': 'Nombre',
      'description': 'Descripción',
      'value': 'Valor',
      'min_value': 'Valor Mínimo',
      'max_value': 'Valor Máximo',
      'current_value': 'Valor Actual',
      'last_measurement': 'Última Medición',
      'date_created': 'Fecha de Creación',
      'date_updated': 'Fecha de Actualización',
      'created_by': 'Creado por',
      'updated_by': 'Actualizado por',
      'actions': 'Acciones',
      'view': 'Ver',
      'details': 'Detalles',
      'settings': 'Configuración',
      'profile': 'Perfil',
      'help': 'Ayuda',
      'about': 'Acerca de',
      'version': 'Versión',
      'copyright': 'Derechos de Autor',
      'privacy': 'Privacidad',
      'terms': 'Términos',
      'contact_us': 'Contáctanos',
      'support': 'Soporte',
      'documentation': 'Documentación',
      'api': 'API',
      'export': 'Exportar',
      'import': 'Importar',
      'download': 'Descargar',
      'upload': 'Subir',
      'refresh': 'Actualizar',
      'reload': 'Recargar',
      'clear': 'Limpiar',
      'reset_filters': 'Restablecer Filtros',
      'apply_filters': 'Aplicar Filtros',
      'no_data': 'No hay datos disponibles',
      'no_results': 'No se encontraron resultados',
      'loading_data': 'Cargando datos...',
      'error_loading': 'Error al cargar los datos',
      'connection_error': 'Error de conexión',
      'server_error': 'Error del servidor',
      'network_error': 'Error de red',
      'timeout_error': 'Error de tiempo de espera',
      'unauthorized': 'No autorizado',
      'forbidden': 'Prohibido',
      'not_found': 'No encontrado',
      'bad_request': 'Solicitud incorrecta',
      'internal_error': 'Error interno',
      'validation_error': 'Error de validación',
      'duplicate_error': 'Error de duplicado',
      'constraint_error': 'Error de restricción',
      'foreign_key_error': 'Error de clave foránea',
      'unique_error': 'Error de unicidad',
      'required_field': 'Campo requerido',
      'invalid_format': 'Formato inválido',
      'invalid_value': 'Valor inválido',
      'min_length': 'Longitud mínima',
      'max_length': 'Longitud máxima',
      'min_value_error': 'Valor mínimo',
      'max_value_error': 'Valor máximo',
      'email_invalid': 'Correo electrónico inválido',
      'password_weak': 'Contraseña débil',
      'password_mismatch': 'Las contraseñas no coinciden',
      'username_taken': 'Nombre de usuario ya existe',
      'email_taken': 'Correo electrónico ya existe',
      'account_locked': 'Cuenta bloqueada',
      'account_disabled': 'Cuenta deshabilitada',
      'session_expired': 'Sesión expirada',
      'login_required': 'Inicio de sesión requerido',
      'permission_denied': 'Permiso denegado',
      'access_denied': 'Acceso denegado',
      'operation_successful': 'Operación exitosa',
      'operation_failed': 'Operación fallida',
      'changes_saved': 'Cambios guardados',
      'changes_discarded': 'Cambios descartados',
      'data_updated': 'Datos actualizados',
      'data_created': 'Datos creados',
      'data_deleted': 'Datos eliminados',
      'data_restored': 'Datos restaurados',
      'backup_created': 'Respaldo creado',
      'backup_restored': 'Respaldo restaurado',
      'settings_updated': 'Configuración actualizada',
      'profile_updated': 'Perfil actualizado',
      'password_changed': 'Contraseña cambiada',
      'email_verified': 'Correo electrónico verificado',
      'account_created': 'Cuenta creada',
      'account_activated': 'Cuenta activada',
      'account_deactivated': 'Cuenta desactivada',
      'account_deleted': 'Cuenta eliminada',
      'user_created': 'Usuario creado',
      'user_updated': 'Usuario actualizado',
      'user_deleted': 'Usuario eliminado',
      'role_assigned': 'Rol asignado',
      'role_removed': 'Rol removido',
      'permission_granted': 'Permiso otorgado',
      'permission_revoked': 'Permiso revocado',
      'notification_sent': 'Notificación enviada',
      'email_sent': 'Correo enviado',
      'sms_sent': 'SMS enviado',
      'push_sent': 'Push enviado',
      'webhook_sent': 'Webhook enviado',
      'api_key_generated': 'Clave API generada',
      'api_key_revoked': 'Clave API revocada',
      'token_generated': 'Token generado',
      'token_revoked': 'Token revocado',
      'session_created': 'Sesión creada',
      'session_ended': 'Sesión terminada',
      'log_created': 'Log creado',
      'audit_log_created': 'Log de auditoría creado',
      'error_log_created': 'Log de error creado',
      'debug_log_created': 'Log de depuración creado',
      'info_log_created': 'Log de información creado',
      'warning_log_created': 'Log de advertencia creado',
      'critical_log_created': 'Log crítico creado',
      'emergency_log_created': 'Log de emergencia creado',
      'alert_created': 'Alerta creada',
      'alert_updated': 'Alerta actualizada',
      'alert_deleted': 'Alerta eliminada',
      'alert_acknowledged': 'Alerta reconocida',
      'alert_resolved': 'Alerta resuelta',
      'alert_escalated': 'Alerta escalada',
      'threshold_exceeded': 'Umbral excedido',
      'threshold_breached': 'Umbral violado',
      'threshold_recovered': 'Umbral recuperado',
      'sensor_offline': 'Sensor fuera de línea',
      'sensor_online': 'Sensor en línea',
      'sensor_error': 'Error del sensor',
      'sensor_warning': 'Advertencia del sensor',
      'sensor_critical': 'Sensor crítico',
      'sensor_normal': 'Sensor normal',
      'measurement_received': 'Medición recibida',
      'measurement_failed': 'Medición fallida',
      'measurement_timeout': 'Medición con tiempo de espera',
      'measurement_invalid': 'Medición inválida',
      'measurement_outdated': 'Medición desactualizada',
      'measurement_duplicate': 'Medición duplicada',
      'measurement_corrupted': 'Medición corrupta',
      'measurement_missing': 'Medición faltante',
      'measurement_delayed': 'Medición retrasada',
      'measurement_early': 'Medición temprana',
      'measurement_late': 'Medición tardía',
      'measurement_anomaly': 'Anomalía en medición',
      'measurement_spike': 'Pico en medición',
      'measurement_drop': 'Caída en medición',
      'measurement_trend_up': 'Tendencia ascendente',
      'measurement_trend_down': 'Tendencia descendente',
      'measurement_trend_stable': 'Tendencia estable',
      'measurement_trend_volatile': 'Tendencia volátil',
      'measurement_trend_cyclical': 'Tendencia cíclica',
      'measurement_trend_seasonal': 'Tendencia estacional',
      'measurement_trend_random': 'Tendencia aleatoria',
      'measurement_trend_linear': 'Tendencia lineal',
      'measurement_trend_exponential': 'Tendencia exponencial',
      'measurement_trend_logarithmic': 'Tendencia logarítmica',
      'measurement_trend_polynomial': 'Tendencia polinomial',
      'measurement_trend_sinusoidal': 'Tendencia sinusoidal',
      'measurement_trend_cosine': 'Tendencia coseno',
      'measurement_trend_tangent': 'Tendencia tangente',
      'measurement_trend_hyperbolic': 'Tendencia hiperbólica',
      'measurement_trend_parabolic': 'Tendencia parabólica',
      'measurement_trend_cubic': 'Tendencia cúbica',
      'measurement_trend_quartic': 'Tendencia cuártica',
      'measurement_trend_quintic': 'Tendencia quíntica',
      'measurement_trend_hexic': 'Tendencia séxtica',
      'measurement_trend_heptic': 'Tendencia séptica',
      'measurement_trend_octic': 'Tendencia óctica',
      'measurement_trend_nonic': 'Tendencia nónica',
      'measurement_trend_decic': 'Tendencia décica',
      'measurement_trend_undecic': 'Tendencia undécica',
      'measurement_trend_dodecic': 'Tendencia dodecica',
      'measurement_trend_tridecic': 'Tendencia tridecica',
      'measurement_trend_tetradecic': 'Tendencia tetradecica',
      'measurement_trend_pentadecic': 'Tendencia pentadecica',
      'measurement_trend_hexadecic': 'Tendencia hexadecica',
      'measurement_trend_heptadecic': 'Tendencia heptadecica',
      'measurement_trend_octadecic': 'Tendencia octadecica',
      'measurement_trend_nondecic': 'Tendencia nondecica',
      'measurement_trend_vigintic': 'Tendencia vigintica',
      'measurement_trend_centic': 'Tendencia centica',
      'measurement_trend_millic': 'Tendencia millica',
      'measurement_trend_megic': 'Tendencia megica',
      'measurement_trend_gigic': 'Tendencia gigica',
      'configuration.title': 'Configuración',
      'configuration.language': 'Idioma',
      'configuration.theme': 'Tema',
      'configuration.advanced': 'Configuración Avanzada',
      'configuration.notifications': 'Notificaciones',
      'configuration.data': 'Datos',
      'configuration.interface': 'Interfaz',
      'configuration.system_info': 'Información del Sistema',
      'configuration.email_alerts': 'Alertas por email',
      'configuration.push_notifications': 'Notificaciones push',
      'configuration.alert_sounds': 'Sonidos de alerta',
      'configuration.auto_refresh': 'Auto-actualización de datos',
      'configuration.offline_mode': 'Modo offline',
      'configuration.smooth_animations': 'Animaciones suaves',
      'configuration.compact_mode': 'Modo compacto',
      'configuration.version': 'Versión',
      'configuration.last_update': 'Última actualización',
      'configuration.active_language': 'Idioma activo',
      'configuration.active_theme': 'Tema activo',
      'configuration.reset': 'Restablecer',
      'configuration.save_changes': 'Guardar Cambios',
      'configuration.select_language': 'Selecciona el idioma de la aplicación:',
      'configuration.select_theme': 'Selecciona el tema visual:',
      'configuration.preview': 'Vista previa:',
      'configuration.current_theme': 'Tema actual:',
      'configuration.light_mode': 'MODO CLARO',
      'configuration.dark_mode': 'MODO OSCURO',
      'configuration.switch_to_light': 'Cambiar a tema claro',
      'configuration.switch_to_dark': 'Cambiar a tema oscuro',
      'configuration.basic': 'BÁSICO',
      'configuration.advanced_toggle': 'AVANZADO',
      'tabs.reports': 'REPORTES',
      'tabs.parameters': 'PARÁMETROS',
      'tabs.configuration': 'CONFIGURACIÓN',
      'tabs.dashboard': 'DASHBOARD',
      'tabs.alerts': 'ALERTAS',
      'tabs.messages': 'MENSAJES',
      'buttons.save': 'GUARDAR',
      'buttons.cancel': 'CANCELAR',
      'buttons.delete': 'ELIMINAR',
      'buttons.edit': 'EDITAR',
      'buttons.create': 'CREAR',
      'buttons.update': 'ACTUALIZAR',
      'buttons.search': 'BUSCAR',
      'buttons.filter': 'FILTRAR',
      'buttons.reset': 'RESTABLECER',
      'buttons.confirm': 'CONFIRMAR',
      'buttons.close': 'CERRAR',
      'buttons.back': 'VOLVER',
      'buttons.next': 'SIGUIENTE',
      'buttons.previous': 'ANTERIOR',
      'buttons.select': 'SELECCIONAR',
      'buttons.all': 'TODOS',
      'buttons.none': 'NINGUNO',
      'buttons.yes': 'SÍ',
      'buttons.no': 'NO',
      'buttons.retry': 'REINTENTAR',
      'status.active': 'ACTIVO',
      'status.inactive': 'INACTIVO',
      'status.enabled': 'HABILITADO',
      'status.disabled': 'DESHABILITADO',
      'status.loading': 'CARGANDO...',
      'status.error': 'ERROR',
      'status.success': 'ÉXITO',
      'status.warning': 'ADVERTENCIA',
      'status.info': 'INFORMACIÓN',
      'forms.select_option': 'SELECCIONA UNA OPCIÓN DEL MENÚ LATERAL PARA CONTINUAR',
      'forms.select_subtab': 'SELECCIONA UNA SUBPESTAÑA PARA CONTINUAR',
      'forms.no_data': 'NO HAY DATOS DISPONIBLES',
      'forms.loading_data': 'CARGANDO DATOS...',
      'forms.error_loading': 'ERROR AL CARGAR LOS DATOS',
      'forms.connection_error': 'ERROR DE CONEXIÓN',
      'forms.server_error': 'ERROR DEL SERVIDOR',
      'forms.network_error': 'ERROR DE RED',
      'forms.timeout_error': 'ERROR DE TIEMPO DE ESPERA',
      'forms.unauthorized': 'NO AUTORIZADO',
      'forms.forbidden': 'PROHIBIDO',
      'forms.not_found': 'NO ENCONTRADO',
      'reports.alerts.title': 'REGISTRO DE ALERTAS',
      'reports.alerts.no_data': 'NO HAY ALERTAS',
      'reports.alerts.total': 'ALERTA(S) TOTAL',
      'reports.alerts.loading': 'CARGANDO ALERTAS...',
      'reports.messages.title': 'REGISTRO DE MENSAJES',
      'reports.messages.no_data': 'NO HAY MENSAJES',
      'reports.messages.total': 'MENSAJE(S) TOTAL',
      'reports.messages.loading': 'CARGANDO MENSAJES...',
      'reports.table.id_alert': 'ID ALERTA',
      'reports.table.threshold_id': 'UMBRAL ID',
      'reports.table.measurement_id': 'MEDICIÓN ID',
      'reports.table.alert_date': 'FECHA ALERTA',
      'reports.table.creator_user': 'USUARIO CREADOR',
      'reports.table.creation_date': 'FECHA CREACIÓN',
      'reports.table.status': 'STATUS',
      'reports.table.alert_id': 'ALERTA ID',
      'reports.table.contact_id': 'CONTACTO ID',
      'reports.table.message': 'MENSAJE',
      'reports.table.date': 'FECHA',
      'dashboard.select_node': 'SELECCIONAR NODO',
      'dashboard.search_node_placeholder': 'Buscar nodo por nombre, DevEUI, ubicación...',
      'dashboard.metrics.temperature': 'Temperatura',
      'dashboard.metrics.humidity': 'Humedad',
      'dashboard.metrics.electroconductivity': 'Electroconductividad',
      'dashboard.no_data': 'SIN DATOS',
      'dashboard.no_data_available': 'SIN DATOS DISPONIBLES',
      'dashboard.detailed_analysis': 'Análisis Detallado',
      'dashboard.date_start': 'FECHA INICIO',
      'dashboard.date_end': 'FECHA FIN',
      'dashboard.tooltip.deveui': 'DevEUI:',
      'dashboard.tooltip.location': 'Ubicación:',
      'dashboard.tooltip.fund': 'Fundo:',
      'dashboard.tooltip.company': 'Empresa:',
      'dashboard.tooltip.country': 'País:',
      'dashboard.tooltip.entity': 'Entidad:',
      'dashboard.tooltip.coordinates': 'Coordenadas:',
      'dashboard.last_measurement': 'Última medida:',
      'dashboard.tooltip.hour': 'Hora:',
      'alerts.filters.title': 'Filtros',
      'alerts.filters.criticality': 'Criticidad',
      'alerts.filters.location': 'Ubicación',
      'alerts.filters.all': 'Todas',
      'parameters.title': 'Parámetros',
      'parameters.groups.location': 'Ubicación',
      'parameters.groups.device': 'Dispositivo',
      'parameters.groups.threshold': 'Umbral',
      'parameters.groups.user': 'Usuario',
      'parameters.tables.country': 'País',
      'parameters.tables.company': 'Empresa',
      'parameters.tables.fund': 'Fundo',
      'parameters.tables.location': 'Ubicación',
      'parameters.tables.localization': 'Localización',
      'parameters.tables.entity': 'Entidad',
      'parameters.tables.type': 'Tipo',
      'parameters.tables.node': 'Nodo',
      'parameters.tables.sensor': 'Sensor',
      'parameters.tables.metric_sensor': 'Métrica Sensor',
      'parameters.tables.metric': 'Métrica',
      'parameters.tables.threshold': 'Umbral',
      'parameters.tables.threshold_profile': 'Perfil Umbral',
      'parameters.tables.audit_log_threshold': 'Audit Log Umbral',
      'parameters.tables.criticality': 'Criticidad',
      'parameters.tables.contact': 'Contacto',
      'parameters.tables.email': 'Correo',
      'parameters.tables.user': 'Usuario',
      'parameters.tables.user_profile': 'Usuario Perfil',
      'parameters.tables.profile': 'Perfil',
      'parameters.operations.status': 'Estado',
      'parameters.operations.create': 'Crear',
      'parameters.operations.update': 'Actualizar',
      'parameters.operations.massive': 'Masivo',
      'parameters.operations.title': 'Operaciones',
      'status.records': 'Registros',
      'status.last_update': 'Última Actualización',
      'status.last_user': 'Último Usuario',
      'status.search_placeholder': 'Buscar en todos los campos...',
      'status.showing_records': 'Mostrando {filtered} de {total} registros',
      'status.loading_columns': 'Cargando columnas...',
      'table_headers.country': 'País',
      'table_headers.company': 'Empresa',
      'table_headers.abbreviation': 'Abreviatura',
      'table_headers.created_by': 'Creado por',
      'table_headers.creation_date': 'Fecha de creación',
      'table_headers.modified_by': 'Modificado por',
      'table_headers.modification_date': 'Fecha de modificación',
      'table_headers.status': 'Status',
      'forms.bad_request': 'SOLICITUD INCORRECTA',
      'forms.internal_error': 'ERROR INTERNO',
      'forms.validation_error': 'ERROR DE VALIDACIÓN',
      'forms.duplicate_error': 'ERROR DE DUPLICADO',
      'forms.constraint_error': 'ERROR DE RESTRICCIÓN',
      'forms.foreign_key_error': 'ERROR DE CLAVE FORÁNEA',
      'forms.unique_error': 'ERROR DE UNICIDAD',
      'forms.required_field': 'CAMPO REQUERIDO',
      'forms.invalid_format': 'FORMATO INVÁLIDO',
      'forms.invalid_value': 'VALOR INVÁLIDO',
      'forms.min_length': 'LONGITUD MÍNIMA',
      'forms.max_length': 'LONGITUD MÁXIMA',
      'forms.min_value_error': 'VALOR MÍNIMO',
      'forms.max_value_error': 'VALOR MÁXIMO',
      'forms.email_invalid': 'CORREO ELECTRÓNICO INVÁLIDO',
      'forms.password_weak': 'CONTRASEÑA DÉBIL',
      'forms.password_mismatch': 'LAS CONTRASEÑAS NO COINCIDEN',
      'forms.username_taken': 'NOMBRE DE USUARIO YA EXISTE',
      'forms.email_taken': 'CORREO ELECTRÓNICO YA EXISTE',
      'forms.account_locked': 'CUENTA BLOQUEADA',
      'forms.account_disabled': 'CUENTA DESHABILITADA',
      'forms.session_expired': 'SESIÓN EXPIRADA',
      'forms.login_required': 'INICIO DE SESIÓN REQUERIDO',
      'forms.permission_denied': 'PERMISO DENEGADO',
      'forms.access_denied': 'ACCESO DENEGADO',
      'forms.operation_successful': 'OPERACIÓN EXITOSA',
      'forms.operation_failed': 'OPERACIÓN FALLIDA',
      'forms.changes_saved': 'CAMBIOS GUARDADOS',
      'forms.changes_discarded': 'CAMBIOS DESCARTADOS',
      'forms.data_updated': 'DATOS ACTUALIZADOS',
      'forms.data_created': 'DATOS CREADOS',
      'forms.data_deleted': 'DATOS ELIMINADOS',
      'forms.data_restored': 'DATOS RESTAURADOS',
      'forms.backup_created': 'RESPALDO CREADO',
      'forms.backup_restored': 'RESPALDO RESTAURADO',
      'forms.settings_updated': 'CONFIGURACIÓN ACTUALIZADA',
      'forms.profile_updated': 'PERFIL ACTUALIZADO',
      'forms.password_changed': 'CONTRASEÑA CAMBIADA',
      'forms.email_verified': 'CORREO ELECTRÓNICO VERIFICADO',
      'forms.account_created': 'CUENTA CREADA',
      'forms.account_activated': 'CUENTA ACTIVADA',
      'forms.account_deactivated': 'CUENTA DESACTIVADA',
      'forms.account_deleted': 'CUENTA ELIMINADA',
      'forms.user_created': 'USUARIO CREADO',
      'forms.user_updated': 'USUARIO ACTUALIZADO',
      'forms.user_deleted': 'USUARIO ELIMINADO',
      'forms.role_assigned': 'ROL ASIGNADO',
      'forms.role_removed': 'ROL REMOVIDO',
      'forms.permission_granted': 'PERMISO OTORGADO',
      'forms.permission_revoked': 'PERMISO REVOCADO',
      'forms.notification_sent': 'NOTIFICACIÓN ENVIADA',
      'forms.email_sent': 'CORREO ENVIADO',
      'forms.sms_sent': 'SMS ENVIADO',
      'forms.push_sent': 'PUSH ENVIADO',
      'forms.webhook_sent': 'WEBHOOK ENVIADO',
      'forms.api_key_generated': 'CLAVE API GENERADA',
      'forms.api_key_revoked': 'CLAVE API REVOCADA',
      'forms.token_generated': 'TOKEN GENERADO',
      'forms.token_revoked': 'TOKEN REVOCADO',
      'forms.session_created': 'SESIÓN CREADA',
      'forms.session_ended': 'SESIÓN TERMINADA',
      'forms.log_created': 'LOG CREADO',
      'forms.audit_log_created': 'LOG DE AUDITORÍA CREADO',
      'forms.error_log_created': 'LOG DE ERROR CREADO',
      'forms.debug_log_created': 'LOG DE DEPURACIÓN CREADO',
      'forms.info_log_created': 'LOG DE INFORMACIÓN CREADO',
      'forms.warning_log_created': 'LOG DE ADVERTENCIA CREADO',
      'forms.critical_log_created': 'LOG CRÍTICO CREADO',
      'forms.emergency_log_created': 'LOG DE EMERGENCIA CREADO',
      'forms.alert_created': 'ALERTA CREADA',
      'forms.alert_updated': 'ALERTA ACTUALIZADA',
      'forms.alert_deleted': 'ALERTA ELIMINADA',
      'forms.alert_acknowledged': 'ALERTA RECONOCIDA',
      'forms.alert_resolved': 'ALERTA RESUELTA',
      'forms.alert_escalated': 'ALERTA ESCALADA',
      'forms.threshold_exceeded': 'UMBRAL EXCEDIDO',
      'forms.threshold_breached': 'UMBRAL VIOLADO',
      'forms.threshold_recovered': 'UMBRAL RECUPERADO',
      'forms.sensor_offline': 'SENSOR FUERA DE LÍNEA',
      'forms.sensor_online': 'SENSOR EN LÍNEA',
      'forms.sensor_error': 'ERROR DEL SENSOR',
      'forms.sensor_warning': 'ADVERTENCIA DEL SENSOR',
      'forms.sensor_critical': 'SENSOR CRÍTICO',
      'forms.sensor_normal': 'SENSOR NORMAL',
      'forms.measurement_received': 'MEDICIÓN RECIBIDA',
      'forms.measurement_failed': 'MEDICIÓN FALLIDA',
      'forms.measurement_timeout': 'MEDICIÓN CON TIEMPO DE ESPERA',
      'forms.measurement_invalid': 'MEDICIÓN INVÁLIDA',
      'forms.measurement_outdated': 'MEDICIÓN DESACTUALIZADA',
      'forms.measurement_duplicate': 'MEDICIÓN DUPLICADA',
      'forms.measurement_corrupted': 'MEDICIÓN CORRUPTA',
      'forms.measurement_missing': 'MEDICIÓN FALTANTE',
      'forms.measurement_delayed': 'MEDICIÓN RETRASADA',
      'forms.measurement_early': 'MEDICIÓN TEMPRANA',
      'forms.measurement_late': 'MEDICIÓN TARDÍA',
      'forms.measurement_anomaly': 'ANOMALÍA EN MEDICIÓN',
      'forms.measurement_spike': 'PICO EN MEDICIÓN',
      'forms.measurement_drop': 'CAÍDA EN MEDICIÓN',
      'forms.measurement_trend_up': 'TENDENCIA ASCENDENTE',
      'forms.measurement_trend_down': 'TENDENCIA DESCENDENTE',
      'forms.measurement_trend_stable': 'TENDENCIA ESTABLE',
      'forms.measurement_trend_volatile': 'TENDENCIA VOLÁTIL',
      'forms.measurement_trend_cyclical': 'TENDENCIA CÍCLICA',
      'forms.measurement_trend_seasonal': 'TENDENCIA ESTACIONAL',
      'forms.measurement_trend_random': 'TENDENCIA ALEATORIA',
      'forms.measurement_trend_linear': 'TENDENCIA LINEAL',
      'forms.measurement_trend_exponential': 'TENDENCIA EXPONENCIAL',
      'forms.measurement_trend_logarithmic': 'TENDENCIA LOGARÍTMICA',
      'forms.measurement_trend_polynomial': 'TENDENCIA POLINOMIAL',
      'forms.measurement_trend_sinusoidal': 'TENDENCIA SINUSOIDAL',
      'forms.measurement_trend_cosine': 'TENDENCIA COSENO',
      'forms.measurement_trend_tangent': 'TENDENCIA TANGENTE',
      'forms.measurement_trend_hyperbolic': 'TENDENCIA HIPERBÓLICA',
      'forms.measurement_trend_parabolic': 'TENDENCIA PARABÓLICA',
      'forms.measurement_trend_cubic': 'TENDENCIA CÚBICA',
      'forms.measurement_trend_quartic': 'TENDENCIA CUÁRTICA',
      'forms.measurement_trend_quintic': 'TENDENCIA QUÍNTICA',
      'forms.measurement_trend_hexic': 'TENDENCIA SÉXTICA',
      'forms.measurement_trend_heptic': 'TENDENCIA SÉPTICA',
      'forms.measurement_trend_octic': 'TENDENCIA ÓCTICA',
      'forms.measurement_trend_nonic': 'TENDENCIA NÓNICA',
      'forms.measurement_trend_decic': 'TENDENCIA DÉCICA',
      'forms.measurement_trend_undecic': 'TENDENCIA UNDÉCICA',
      'forms.measurement_trend_dodecic': 'TENDENCIA DODECICA',
      'forms.measurement_trend_tridecic': 'TENDENCIA TRIDECICA',
      'forms.measurement_trend_tetradecic': 'TENDENCIA TETRADECICA',
      'forms.measurement_trend_pentadecic': 'TENDENCIA PENTADECICA',
      'forms.measurement_trend_hexadecic': 'TENDENCIA HEXADECICA',
      'forms.measurement_trend_heptadecic': 'TENDENCIA HEPTADECICA',
      'forms.measurement_trend_octadecic': 'TENDENCIA OCTADECICA',
      'forms.measurement_trend_nondecic': 'TENDENCIA NONDECICA',
      'forms.measurement_trend_vigintic': 'TENDENCIA VIGINTICA',
      'forms.measurement_trend_centic': 'TENDENCIA CENTICA',
      'forms.measurement_trend_millic': 'TENDENCIA MILLICA',
      'forms.measurement_trend_megic': 'TENDENCIA MEGICA',
      'forms.measurement_trend_gigic': 'TENDENCIA GIGICA',
      'subtabs.status': 'ESTADO',
      'subtabs.insert': 'CREAR',
      'subtabs.update': 'ACTUALIZAR',
      'subtabs.massive': 'MASIVO',
      'subtabs.alerts': 'ALERTAS',
      'subtabs.messages': 'MENSAJES',
      'subtabs.dashboard': 'DASHBOARD',
      'fields.country': 'PAÍS',
      'fields.company': 'EMPRESA',
      'fields.fund': 'FUNDO',
      'fields.location': 'UBICACIÓN',
      'fields.entity': 'ENTIDAD',
      'fields.node': 'NODO',
      'fields.sensor': 'SENSOR',
      'fields.metric': 'MÉTRICA',
      'fields.type': 'TIPO',
      'fields.measurement': 'MEDICIÓN',
      'fields.threshold': 'UMBRAL',
      'fields.alert': 'ALERTA',
      'fields.user': 'USUARIO',
      'fields.medium': 'MEDIO',
      'fields.contact': 'CONTACTO',
      'fields.localization': 'LOCALIZACIÓN',
      'fields.sensor_metric': 'MÉTRICA SENSOR',
      'fields.threshold_profile': 'PERFIL UMBRAL',
      'fields.audit_log_threshold': 'AUDIT LOG UMBRAL',
      'fields.criticality': 'CRITICIDAD',
      'fields.name': 'NOMBRE',
      'fields.description': 'DESCRIPCIÓN',
      'fields.value': 'VALOR',
      'fields.min_value': 'VALOR MÍNIMO',
      'fields.max_value': 'VALOR MÁXIMO',
      'fields.current_value': 'VALOR ACTUAL',
      'fields.last_measurement': 'ÚLTIMA MEDICIÓN',
      'fields.date_created': 'FECHA DE CREACIÓN',
      'fields.date_updated': 'FECHA DE ACTUALIZACIÓN',
      'fields.created_by': 'CREADO POR',
      'fields.updated_by': 'ACTUALIZADO POR',
      'fields.actions': 'ACCIONES',
      'fields.view': 'VER',
      'fields.details': 'DETALLES',
      'fields.settings': 'CONFIGURACIÓN',
      'fields.profile': 'PERFIL',
      'fields.help': 'AYUDA',
      'fields.about': 'ACERCA DE',
      'fields.version': 'VERSIÓN',
      'fields.copyright': 'DERECHOS DE AUTOR',
      'fields.privacy': 'PRIVACIDAD',
      'fields.terms': 'TÉRMINOS',
      'fields.contact_us': 'CONTÁCTANOS',
      'fields.support': 'SOPORTE',
      'fields.documentation': 'DOCUMENTACIÓN',
      'fields.api': 'API',
      'fields.export': 'EXPORTAR',
      'fields.import': 'IMPORTAR',
      'fields.download': 'DESCARGAR',
      'fields.upload': 'SUBIR',
      'fields.refresh': 'ACTUALIZAR',
      'fields.reload': 'RECARGAR',
      'fields.clear': 'LIMPIAR',
      'fields.reset_filters': 'RESTABLECER FILTROS',
      'fields.apply_filters': 'APLICAR FILTROS',
      'fields.no_data': 'NO HAY DATOS DISPONIBLES',
      'fields.no_results': 'NO SE ENCONTRARON RESULTADOS',
      'fields.loading_data': 'CARGANDO DATOS...',
      'fields.error_loading': 'ERROR AL CARGAR LOS DATOS',
      'fields.connection_error': 'ERROR DE CONEXIÓN',
      'fields.server_error': 'ERROR DEL SERVIDOR',
      'fields.network_error': 'ERROR DE RED',
      'fields.timeout_error': 'ERROR DE TIEMPO DE ESPERA',
      'fields.unauthorized': 'NO AUTORIZADO',
      'fields.forbidden': 'PROHIBIDO',
      'fields.not_found': 'NO ENCONTRADO',
      'fields.bad_request': 'SOLICITUD INCORRECTA',
      'fields.internal_error': 'ERROR INTERNO',
      'fields.validation_error': 'ERROR DE VALIDACIÓN',
      'fields.duplicate_error': 'ERROR DE DUPLICADO',
      'fields.constraint_error': 'ERROR DE RESTRICCIÓN',
      'fields.foreign_key_error': 'ERROR DE CLAVE FORÁNEA',
      'fields.unique_error': 'ERROR DE UNICIDAD',
      'fields.required_field': 'CAMPO REQUERIDO',
      'fields.invalid_format': 'FORMATO INVÁLIDO',
      'fields.invalid_value': 'VALOR INVÁLIDO',
      'fields.min_length': 'LONGITUD MÍNIMA',
      'fields.max_length': 'LONGITUD MÁXIMA',
      'fields.min_value_error': 'VALOR MÍNIMO',
      'fields.max_value_error': 'VALOR MÁXIMO',
      'fields.email_invalid': 'CORREO ELECTRÓNICO INVÁLIDO',
      'fields.password_weak': 'CONTRASEÑA DÉBIL',
      'fields.password_mismatch': 'LAS CONTRASEÑAS NO COINCIDEN',
      'fields.username_taken': 'NOMBRE DE USUARIO YA EXISTE',
      'fields.email_taken': 'CORREO ELECTRÓNICO YA EXISTE',
      'fields.account_locked': 'CUENTA BLOQUEADA',
      'fields.account_disabled': 'CUENTA DESHABILITADA',
      'fields.session_expired': 'SESIÓN EXPIRADA',
      'fields.login_required': 'INICIO DE SESIÓN REQUERIDO',
      'fields.permission_denied': 'PERMISO DENEGADO',
      'fields.access_denied': 'ACCESO DENEGADO',
      'fields.operation_successful': 'OPERACIÓN EXITOSA',
      'fields.operation_failed': 'OPERACIÓN FALLIDA',
      'fields.changes_saved': 'CAMBIOS GUARDADOS',
      'fields.changes_discarded': 'CAMBIOS DESCARTADOS',
      'fields.data_updated': 'DATOS ACTUALIZADOS',
      'fields.data_created': 'DATOS CREADOS',
      'fields.data_deleted': 'DATOS ELIMINADOS',
      'fields.data_restored': 'DATOS RESTAURADOS',
      'fields.backup_created': 'RESPALDO CREADO',
      'fields.backup_restored': 'RESPALDO RESTAURADO',
      'fields.settings_updated': 'CONFIGURACIÓN ACTUALIZADA',
      'fields.profile_updated': 'PERFIL ACTUALIZADO',
      'fields.password_changed': 'CONTRASEÑA CAMBIADA',
      'fields.email_verified': 'CORREO ELECTRÓNICO VERIFICADO',
      'fields.account_created': 'CUENTA CREADA',
      'fields.account_activated': 'CUENTA ACTIVADA',
      'fields.account_deactivated': 'CUENTA DESACTIVADA',
      'fields.account_deleted': 'CUENTA ELIMINADA',
      'fields.user_created': 'USUARIO CREADO',
      'fields.user_updated': 'USUARIO ACTUALIZADO',
      'fields.user_deleted': 'USUARIO ELIMINADO',
      'fields.role_assigned': 'ROL ASIGNADO',
      'fields.role_removed': 'ROL REMOVIDO',
      'fields.permission_granted': 'PERMISO OTORGADO',
      'fields.permission_revoked': 'PERMISO REVOCADO',
      'fields.notification_sent': 'NOTIFICACIÓN ENVIADA',
      'fields.email_sent': 'CORREO ENVIADO',
      'fields.sms_sent': 'SMS ENVIADO',
      'fields.push_sent': 'PUSH ENVIADO',
      'fields.webhook_sent': 'WEBHOOK ENVIADO',
      'fields.api_key_generated': 'CLAVE API GENERADA',
      'fields.api_key_revoked': 'CLAVE API REVOCADA',
      'fields.token_generated': 'TOKEN GENERADO',
      'fields.token_revoked': 'TOKEN REVOCADO',
      'fields.session_created': 'SESIÓN CREADA',
      'fields.session_ended': 'SESIÓN TERMINADA',
      'fields.log_created': 'LOG CREADO',
      'fields.audit_log_created': 'LOG DE AUDITORÍA CREADO',
      'fields.error_log_created': 'LOG DE ERROR CREADO',
      'fields.debug_log_created': 'LOG DE DEPURACIÓN CREADO',
      'fields.info_log_created': 'LOG DE INFORMACIÓN CREADO',
      'fields.warning_log_created': 'LOG DE ADVERTENCIA CREADO',
      'fields.critical_log_created': 'LOG CRÍTICO CREADO',
      'fields.emergency_log_created': 'LOG DE EMERGENCIA CREADO',
      'fields.alert_created': 'ALERTA CREADA',
      'fields.alert_updated': 'ALERTA ACTUALIZADA',
      'fields.alert_deleted': 'ALERTA ELIMINADA',
      'fields.alert_acknowledged': 'ALERTA RECONOCIDA',
      'fields.alert_resolved': 'ALERTA RESUELTA',
      'fields.alert_escalated': 'ALERTA ESCALADA',
      'fields.threshold_exceeded': 'UMBRAL EXCEDIDO',
      'fields.threshold_breached': 'UMBRAL VIOLADO',
      'fields.threshold_recovered': 'UMBRAL RECUPERADO',
      'fields.sensor_offline': 'SENSOR FUERA DE LÍNEA',
      'fields.sensor_online': 'SENSOR EN LÍNEA',
      'fields.sensor_error': 'ERROR DEL SENSOR',
      'fields.sensor_warning': 'ADVERTENCIA DEL SENSOR',
      'fields.sensor_critical': 'SENSOR CRÍTICO',
      'fields.sensor_normal': 'SENSOR NORMAL',
      'fields.measurement_received': 'MEDICIÓN RECIBIDA',
      'fields.measurement_failed': 'MEDICIÓN FALLIDA',
      'fields.measurement_timeout': 'MEDICIÓN CON TIEMPO DE ESPERA',
      'fields.measurement_invalid': 'MEDICIÓN INVÁLIDA',
      'fields.measurement_outdated': 'MEDICIÓN DESACTUALIZADA',
      'fields.measurement_duplicate': 'MEDICIÓN DUPLICADA',
      'fields.measurement_corrupted': 'MEDICIÓN CORRUPTA',
      'fields.measurement_missing': 'MEDICIÓN FALTANTE',
      'fields.measurement_delayed': 'MEDICIÓN RETRASADA',
      'fields.measurement_early': 'MEDICIÓN TEMPRANA',
      'fields.measurement_late': 'MEDICIÓN TARDÍA',
      'fields.measurement_anomaly': 'ANOMALÍA EN MEDICIÓN',
      'fields.measurement_spike': 'PICO EN MEDICIÓN',
      'fields.measurement_drop': 'CAÍDA EN MEDICIÓN',
      'fields.measurement_trend_up': 'TENDENCIA ASCENDENTE',
      'fields.measurement_trend_down': 'TENDENCIA DESCENDENTE',
      'fields.measurement_trend_stable': 'TENDENCIA ESTABLE',
      'fields.measurement_trend_volatile': 'TENDENCIA VOLÁTIL',
      'fields.measurement_trend_cyclical': 'TENDENCIA CÍCLICA',
      'fields.measurement_trend_seasonal': 'TENDENCIA ESTACIONAL',
      'fields.measurement_trend_random': 'TENDENCIA ALEATORIA',
      'fields.measurement_trend_linear': 'TENDENCIA LINEAL',
      'fields.measurement_trend_exponential': 'TENDENCIA EXPONENCIAL',
      'fields.measurement_trend_logarithmic': 'TENDENCIA LOGARÍTMICA',
      'fields.measurement_trend_polynomial': 'TENDENCIA POLINOMIAL',
      'fields.measurement_trend_sinusoidal': 'TENDENCIA SINUSOIDAL',
      'fields.measurement_trend_cosine': 'TENDENCIA COSENO',
      'fields.measurement_trend_tangent': 'TENDENCIA TANGENTE',
      'fields.measurement_trend_hyperbolic': 'TENDENCIA HIPERBÓLICA',
      'fields.measurement_trend_parabolic': 'TENDENCIA PARABÓLICA',
      'fields.measurement_trend_cubic': 'TENDENCIA CÚBICA',
      'fields.measurement_trend_quartic': 'TENDENCIA CUÁRTICA',
      'fields.measurement_trend_quintic': 'TENDENCIA QUÍNTICA',
      'fields.measurement_trend_hexic': 'TENDENCIA SÉXTICA',
      'fields.measurement_trend_heptic': 'TENDENCIA SÉPTICA',
      'fields.measurement_trend_octic': 'TENDENCIA ÓCTICA',
      'fields.measurement_trend_nonic': 'TENDENCIA NÓNICA',
      'fields.measurement_trend_decic': 'TENDENCIA DÉCICA',
      'fields.measurement_trend_undecic': 'TENDENCIA UNDÉCICA',
      'fields.measurement_trend_dodecic': 'TENDENCIA DODECICA',
      'fields.measurement_trend_tridecic': 'TENDENCIA TRIDECICA',
      'fields.measurement_trend_tetradecic': 'TENDENCIA TETRADECICA',
      'fields.measurement_trend_pentadecic': 'TENDENCIA PENTADECICA',
      'fields.measurement_trend_hexadecic': 'TENDENCIA HEXADECICA',
      'fields.measurement_trend_heptadecic': 'TENDENCIA HEPTADECICA',
      'fields.measurement_trend_octadecic': 'TENDENCIA OCTADECICA',
      'fields.measurement_trend_nondecic': 'TENDENCIA NONDECICA',
      'fields.measurement_trend_vigintic': 'TENDENCIA VIGINTICA',
      'fields.measurement_trend_centic': 'TENDENCIA CENTICA',
      'fields.measurement_trend_millic': 'TENDENCIA MILLICA',
      'fields.measurement_trend_megic': 'TENDENCIA MEGICA',
      'fields.measurement_trend_gigic': 'TENDENCIA GIGICA',
    },
    en: {
      'welcome.title': 'Welcome to JoySense Dashboard',
      'welcome.subtitle': 'Intelligent Monitoring System',
      'dashboard.title': 'Dashboard',
      'reports.title': 'Reports',
      'alerts.title': 'Alerts',
      'messages.title': 'Messages',
      'login.title': 'Sign In',
      'login.subtitle': 'Access your account',
      'login.email': 'Email',
      'login.password': 'Password',
      'login.button': 'Sign In',
      'login.error': 'Invalid credentials',
      'logout.button': 'Sign Out',
      'loading': 'Loading...',
      'error': 'Error',
      'success': 'Success',
      'warning': 'Warning',
      'info': 'Information',
      'save': 'Save',
      'cancel': 'Cancel',
      'delete': 'Delete',
      'edit': 'Edit',
      'create': 'Create',
      'update': 'Update',
      'search': 'Search',
      'filter': 'Filter',
      'reset': 'Reset',
      'confirm': 'Confirm',
      'yes': 'Yes',
      'no': 'No',
      'close': 'Close',
      'back': 'Back',
      'next': 'Next',
      'previous': 'Previous',
      'select': 'Select',
      'all': 'All',
      'none': 'None',
      'status': 'Status',
      'active': 'Active',
      'inactive': 'Inactive',
      'enabled': 'Enabled',
      'disabled': 'Disabled',
      'country': 'Country',
      'company': 'Company',
      'fund': 'Fund',
      'location': 'Location',
      'entity': 'Entity',
      'node': 'Node',
      'sensor': 'Sensor',
      'metric': 'Metric',
      'type': 'Type',
      'measurement': 'Measurement',
      'threshold': 'Threshold',
      'alert': 'Alert',
      'user': 'User',
      'medium': 'Medium',
      'contact': 'Contact',
      'localization': 'Localization',
      'sensor_metric': 'Sensor Metric',
      'threshold_profile': 'Threshold Profile',
      'audit_log_threshold': 'Audit Log Threshold',
      'criticality': 'Criticality',
      'name': 'Name',
      'description': 'Description',
      'value': 'Value',
      'min_value': 'Min Value',
      'max_value': 'Max Value',
      'current_value': 'Current Value',
      'last_measurement': 'Last Measurement',
      'date_created': 'Date Created',
      'date_updated': 'Date Updated',
      'created_by': 'Created By',
      'updated_by': 'Updated By',
      'actions': 'Actions',
      'view': 'View',
      'details': 'Details',
      'settings': 'Settings',
      'profile': 'Profile',
      'help': 'Help',
      'about': 'About',
      'version': 'Version',
      'copyright': 'Copyright',
      'privacy': 'Privacy',
      'terms': 'Terms',
      'contact_us': 'Contact Us',
      'support': 'Support',
      'documentation': 'Documentation',
      'api': 'API',
      'export': 'Export',
      'import': 'Import',
      'download': 'Download',
      'upload': 'Upload',
      'refresh': 'Refresh',
      'reload': 'Reload',
      'clear': 'Clear',
      'reset_filters': 'Reset Filters',
      'apply_filters': 'Apply Filters',
      'no_data': 'No data available',
      'no_results': 'No results found',
      'loading_data': 'Loading data...',
      'error_loading': 'Error loading data',
      'connection_error': 'Connection error',
      'server_error': 'Server error',
      'network_error': 'Network error',
      'timeout_error': 'Timeout error',
      'unauthorized': 'Unauthorized',
      'forbidden': 'Forbidden',
      'not_found': 'Not found',
      'bad_request': 'Bad request',
      'internal_error': 'Internal error',
      'validation_error': 'Validation error',
      'duplicate_error': 'Duplicate error',
      'constraint_error': 'Constraint error',
      'foreign_key_error': 'Foreign key error',
      'unique_error': 'Unique error',
      'required_field': 'Required field',
      'invalid_format': 'Invalid format',
      'invalid_value': 'Invalid value',
      'min_length': 'Minimum length',
      'max_length': 'Maximum length',
      'min_value_error': 'Minimum value',
      'max_value_error': 'Maximum value',
      'email_invalid': 'Invalid email',
      'password_weak': 'Weak password',
      'password_mismatch': 'Passwords do not match',
      'username_taken': 'Username already exists',
      'email_taken': 'Email already exists',
      'account_locked': 'Account locked',
      'account_disabled': 'Account disabled',
      'session_expired': 'Session expired',
      'login_required': 'Login required',
      'permission_denied': 'Permission denied',
      'access_denied': 'Access denied',
      'operation_successful': 'Operation successful',
      'operation_failed': 'Operation failed',
      'changes_saved': 'Changes saved',
      'changes_discarded': 'Changes discarded',
      'data_updated': 'Data updated',
      'data_created': 'Data created',
      'data_deleted': 'Data deleted',
      'data_restored': 'Data restored',
      'backup_created': 'Backup created',
      'backup_restored': 'Backup restored',
      'settings_updated': 'Settings updated',
      'profile_updated': 'Profile updated',
      'password_changed': 'Password changed',
      'email_verified': 'Email verified',
      'account_created': 'Account created',
      'account_activated': 'Account activated',
      'account_deactivated': 'Account deactivated',
      'account_deleted': 'Account deleted',
      'user_created': 'User created',
      'user_updated': 'User updated',
      'user_deleted': 'User deleted',
      'role_assigned': 'Role assigned',
      'role_removed': 'Role removed',
      'permission_granted': 'Permission granted',
      'permission_revoked': 'Permission revoked',
      'notification_sent': 'Notification sent',
      'email_sent': 'Email sent',
      'sms_sent': 'SMS sent',
      'push_sent': 'Push sent',
      'webhook_sent': 'Webhook sent',
      'api_key_generated': 'API key generated',
      'api_key_revoked': 'API key revoked',
      'token_generated': 'Token generated',
      'token_revoked': 'Token revoked',
      'session_created': 'Session created',
      'session_ended': 'Session ended',
      'log_created': 'Log created',
      'audit_log_created': 'Audit log created',
      'error_log_created': 'Error log created',
      'debug_log_created': 'Debug log created',
      'info_log_created': 'Info log created',
      'warning_log_created': 'Warning log created',
      'critical_log_created': 'Critical log created',
      'emergency_log_created': 'Emergency log created',
      'alert_created': 'Alert created',
      'alert_updated': 'Alert updated',
      'alert_deleted': 'Alert deleted',
      'alert_acknowledged': 'Alert acknowledged',
      'alert_resolved': 'Alert resolved',
      'alert_escalated': 'Alert escalated',
      'threshold_exceeded': 'Threshold exceeded',
      'threshold_breached': 'Threshold breached',
      'threshold_recovered': 'Threshold recovered',
      'sensor_offline': 'Sensor offline',
      'sensor_online': 'Sensor online',
      'sensor_error': 'Sensor error',
      'sensor_warning': 'Sensor warning',
      'sensor_critical': 'Sensor critical',
      'sensor_normal': 'Sensor normal',
      'measurement_received': 'Measurement received',
      'measurement_failed': 'Measurement failed',
      'measurement_timeout': 'Measurement timeout',
      'measurement_invalid': 'Invalid measurement',
      'measurement_outdated': 'Outdated measurement',
      'measurement_duplicate': 'Duplicate measurement',
      'measurement_corrupted': 'Corrupted measurement',
      'measurement_missing': 'Missing measurement',
      'measurement_delayed': 'Delayed measurement',
      'measurement_early': 'Early measurement',
      'measurement_late': 'Late measurement',
      'measurement_anomaly': 'Measurement anomaly',
      'measurement_spike': 'Measurement spike',
      'measurement_drop': 'Measurement drop',
      'measurement_trend_up': 'Upward trend',
      'measurement_trend_down': 'Downward trend',
      'measurement_trend_stable': 'Stable trend',
      'measurement_trend_volatile': 'Volatile trend',
      'measurement_trend_cyclical': 'Cyclical trend',
      'measurement_trend_seasonal': 'Seasonal trend',
      'measurement_trend_random': 'Random trend',
      'measurement_trend_linear': 'Linear trend',
      'measurement_trend_exponential': 'Exponential trend',
      'measurement_trend_logarithmic': 'Logarithmic trend',
      'measurement_trend_polynomial': 'Polynomial trend',
      'measurement_trend_sinusoidal': 'Sinusoidal trend',
      'measurement_trend_cosine': 'Cosine trend',
      'measurement_trend_tangent': 'Tangent trend',
      'measurement_trend_hyperbolic': 'Hyperbolic trend',
      'measurement_trend_parabolic': 'Parabolic trend',
      'measurement_trend_cubic': 'Cubic trend',
      'measurement_trend_quartic': 'Quartic trend',
      'measurement_trend_quintic': 'Quintic trend',
      'measurement_trend_hexic': 'Hexic trend',
      'measurement_trend_heptic': 'Heptic trend',
      'measurement_trend_octic': 'Octic trend',
      'measurement_trend_nonic': 'Nonic trend',
      'measurement_trend_decic': 'Decic trend',
      'measurement_trend_undecic': 'Undecic trend',
      'measurement_trend_dodecic': 'Dodecic trend',
      'measurement_trend_tridecic': 'Tridecic trend',
      'measurement_trend_tetradecic': 'Tetradecic trend',
      'measurement_trend_pentadecic': 'Pentadecic trend',
      'measurement_trend_hexadecic': 'Hexadecic trend',
      'measurement_trend_heptadecic': 'Heptadecic trend',
      'measurement_trend_octadecic': 'Octadecic trend',
      'measurement_trend_nondecic': 'Nondecic trend',
      'measurement_trend_vigintic': 'Vigintic trend',
      'measurement_trend_centic': 'Centic trend',
      'measurement_trend_millic': 'Millic trend',
      'measurement_trend_megic': 'Megic trend',
      'measurement_trend_gigic': 'Gigic trend',
      'measurement_trend_teric': 'Teric trend',
      'measurement_trend_petic': 'Petic trend',
      'measurement_trend_exic': 'Exic trend',
      'measurement_trend_zetic': 'Zetic trend',
      'measurement_trend_yotic': 'Yotic trend',
      'measurement_trend_ronnic': 'Ronnic trend',
      'measurement_trend_quetic': 'Quetic trend',
      'configuration.title': 'Configuration',
      'configuration.language': 'Language',
      'configuration.theme': 'Theme',
      'configuration.advanced': 'Advanced Configuration',
      'configuration.notifications': 'Notifications',
      'configuration.data': 'Data',
      'configuration.interface': 'Interface',
      'configuration.system_info': 'System Information',
      'configuration.email_alerts': 'Email alerts',
      'configuration.push_notifications': 'Push notifications',
      'configuration.alert_sounds': 'Alert sounds',
      'configuration.auto_refresh': 'Auto-refresh data',
      'configuration.offline_mode': 'Offline mode',
      'configuration.smooth_animations': 'Smooth animations',
      'configuration.compact_mode': 'Compact mode',
      'configuration.version': 'Version',
      'configuration.last_update': 'Last update',
      'configuration.active_language': 'Active language',
      'configuration.active_theme': 'Active theme',
      'configuration.reset': 'Reset',
      'configuration.save_changes': 'Save Changes',
      'configuration.select_language': 'Select application language:',
      'configuration.select_theme': 'Select visual theme:',
      'configuration.preview': 'Preview:',
      'configuration.current_theme': 'Current theme:',
      'configuration.light_mode': 'LIGHT MODE',
      'configuration.dark_mode': 'DARK MODE',
      'configuration.switch_to_light': 'Switch to light theme',
      'configuration.switch_to_dark': 'Switch to dark theme',
      'configuration.basic': 'BASIC',
      'configuration.advanced_toggle': 'ADVANCED',
      'tabs.reports': 'REPORTS',
      'tabs.parameters': 'PARAMETERS',
      'tabs.configuration': 'CONFIGURATION',
      'tabs.dashboard': 'DASHBOARD',
      'tabs.alerts': 'ALERTS',
      'tabs.messages': 'MESSAGES',
      'buttons.save': 'SAVE',
      'buttons.cancel': 'CANCEL',
      'buttons.delete': 'DELETE',
      'buttons.edit': 'EDIT',
      'buttons.create': 'CREATE',
      'buttons.update': 'UPDATE',
      'buttons.search': 'SEARCH',
      'buttons.filter': 'FILTER',
      'buttons.reset': 'RESET',
      'buttons.confirm': 'CONFIRM',
      'buttons.close': 'CLOSE',
      'buttons.back': 'BACK',
      'buttons.next': 'NEXT',
      'buttons.previous': 'PREVIOUS',
      'buttons.select': 'SELECT',
      'buttons.all': 'ALL',
      'buttons.none': 'NONE',
      'buttons.yes': 'YES',
      'buttons.no': 'NO',
      'buttons.retry': 'RETRY',
      'status.active': 'ACTIVE',
      'status.inactive': 'INACTIVE',
      'status.enabled': 'ENABLED',
      'status.disabled': 'DISABLED',
      'status.loading': 'LOADING...',
      'status.error': 'ERROR',
      'status.success': 'SUCCESS',
      'status.warning': 'WARNING',
      'status.info': 'INFORMATION',
      'forms.select_option': 'SELECT AN OPTION FROM THE SIDEBAR MENU TO CONTINUE',
      'forms.select_subtab': 'SELECT A SUBTAB TO CONTINUE',
      'forms.no_data': 'NO DATA AVAILABLE',
      'forms.loading_data': 'LOADING DATA...',
      'forms.error_loading': 'ERROR LOADING DATA',
      'forms.connection_error': 'CONNECTION ERROR',
      'forms.server_error': 'SERVER ERROR',
      'forms.network_error': 'NETWORK ERROR',
      'forms.timeout_error': 'TIMEOUT ERROR',
      'forms.unauthorized': 'UNAUTHORIZED',
      'forms.forbidden': 'FORBIDDEN',
      'forms.not_found': 'NOT FOUND',
      'reports.alerts.title': 'ALERTS REGISTRY',
      'reports.alerts.no_data': 'NO ALERTS',
      'reports.alerts.total': 'TOTAL ALERT(S)',
      'reports.alerts.loading': 'LOADING ALERTS...',
      'reports.messages.title': 'MESSAGES REGISTRY',
      'reports.messages.no_data': 'NO MESSAGES',
      'reports.messages.total': 'TOTAL MESSAGE(S)',
      'reports.messages.loading': 'LOADING MESSAGES...',
      'reports.table.id_alert': 'ALERT ID',
      'reports.table.threshold_id': 'THRESHOLD ID',
      'reports.table.measurement_id': 'MEASUREMENT ID',
      'reports.table.alert_date': 'ALERT DATE',
      'reports.table.creator_user': 'CREATOR USER',
      'reports.table.creation_date': 'CREATION DATE',
      'reports.table.status': 'STATUS',
      'reports.table.alert_id': 'ALERT ID',
      'reports.table.contact_id': 'CONTACT ID',
      'reports.table.message': 'MESSAGE',
      'reports.table.date': 'DATE',
      'dashboard.select_node': 'SELECT NODE',
      'dashboard.search_node_placeholder': 'Search node by name, DevEUI, location...',
      'dashboard.metrics.temperature': 'Temperature',
      'dashboard.metrics.humidity': 'Humidity',
      'dashboard.metrics.electroconductivity': 'Electroconductivity',
      'dashboard.no_data': 'NO DATA',
      'dashboard.no_data_available': 'NO DATA AVAILABLE',
      'dashboard.detailed_analysis': 'Detailed Analysis',
      'dashboard.date_start': 'START DATE',
      'dashboard.date_end': 'END DATE',
      'dashboard.tooltip.deveui': 'DevEUI:',
      'dashboard.tooltip.location': 'Location:',
      'dashboard.tooltip.fund': 'Fund:',
      'dashboard.tooltip.company': 'Company:',
      'dashboard.tooltip.country': 'Country:',
      'dashboard.tooltip.entity': 'Entity:',
      'dashboard.tooltip.coordinates': 'Coordinates:',
      'dashboard.last_measurement': 'Last measurement:',
      'dashboard.tooltip.hour': 'Hour:',
      'alerts.filters.title': 'Filters',
      'alerts.filters.criticality': 'Criticality',
      'alerts.filters.location': 'Location',
      'alerts.filters.all': 'All',
      'parameters.title': 'Parameters',
      'parameters.groups.location': 'Location',
      'parameters.groups.device': 'Device',
      'parameters.groups.threshold': 'Threshold',
      'parameters.groups.user': 'User',
      'parameters.tables.country': 'Country',
      'parameters.tables.company': 'Company',
      'parameters.tables.fund': 'Fund',
      'parameters.tables.location': 'Location',
      'parameters.tables.localization': 'Localization',
      'parameters.tables.entity': 'Entity',
      'parameters.tables.type': 'Type',
      'parameters.tables.node': 'Node',
      'parameters.tables.sensor': 'Sensor',
      'parameters.tables.metric_sensor': 'Metric Sensor',
      'parameters.tables.metric': 'Metric',
      'parameters.tables.threshold': 'Threshold',
      'parameters.tables.threshold_profile': 'Threshold Profile',
      'parameters.tables.audit_log_threshold': 'Audit Log Threshold',
      'parameters.tables.criticality': 'Criticality',
      'parameters.tables.contact': 'Contact',
      'parameters.tables.email': 'Email',
      'parameters.tables.user': 'User',
      'parameters.tables.user_profile': 'User Profile',
      'parameters.tables.profile': 'Profile',
      'parameters.operations.status': 'Status',
      'parameters.operations.create': 'Create',
      'parameters.operations.update': 'Update',
      'parameters.operations.massive': 'Massive',
      'parameters.operations.title': 'Operations',
      'status.records': 'Records',
      'status.last_update': 'Last Update',
      'status.last_user': 'Last User',
      'status.search_placeholder': 'Search in all fields...',
      'status.showing_records': 'Showing {filtered} of {total} records',
      'status.loading_columns': 'Loading columns...',
      'table_headers.country': 'Country',
      'table_headers.company': 'Company',
      'table_headers.abbreviation': 'Abbreviation',
      'table_headers.created_by': 'Created by',
      'table_headers.creation_date': 'Creation date',
      'table_headers.modified_by': 'Modified by',
      'table_headers.modification_date': 'Modification date',
      'table_headers.status': 'Status',
      'forms.bad_request': 'BAD REQUEST',
      'forms.internal_error': 'INTERNAL ERROR',
      'forms.validation_error': 'VALIDATION ERROR',
      'forms.duplicate_error': 'DUPLICATE ERROR',
      'forms.constraint_error': 'CONSTRAINT ERROR',
      'forms.foreign_key_error': 'FOREIGN KEY ERROR',
      'forms.unique_error': 'UNIQUE ERROR',
      'forms.required_field': 'REQUIRED FIELD',
      'forms.invalid_format': 'INVALID FORMAT',
      'forms.invalid_value': 'INVALID VALUE',
      'forms.min_length': 'MINIMUM LENGTH',
      'forms.max_length': 'MAXIMUM LENGTH',
      'forms.min_value_error': 'MINIMUM VALUE',
      'forms.max_value_error': 'MAXIMUM VALUE',
      'forms.email_invalid': 'INVALID EMAIL',
      'forms.password_weak': 'WEAK PASSWORD',
      'forms.password_mismatch': 'PASSWORDS DO NOT MATCH',
      'forms.username_taken': 'USERNAME ALREADY EXISTS',
      'forms.email_taken': 'EMAIL ALREADY EXISTS',
      'forms.account_locked': 'ACCOUNT LOCKED',
      'forms.account_disabled': 'ACCOUNT DISABLED',
      'forms.session_expired': 'SESSION EXPIRED',
      'forms.login_required': 'LOGIN REQUIRED',
      'forms.permission_denied': 'PERMISSION DENIED',
      'forms.access_denied': 'ACCESS DENIED',
      'forms.operation_successful': 'OPERATION SUCCESSFUL',
      'forms.operation_failed': 'OPERATION FAILED',
      'forms.changes_saved': 'CHANGES SAVED',
      'forms.changes_discarded': 'CHANGES DISCARDED',
      'forms.data_updated': 'DATA UPDATED',
      'forms.data_created': 'DATA CREATED',
      'forms.data_deleted': 'DATA DELETED',
      'forms.data_restored': 'DATA RESTORED',
      'forms.backup_created': 'BACKUP CREATED',
      'forms.backup_restored': 'BACKUP RESTORED',
      'forms.settings_updated': 'SETTINGS UPDATED',
      'forms.profile_updated': 'PROFILE UPDATED',
      'forms.password_changed': 'PASSWORD CHANGED',
      'forms.email_verified': 'EMAIL VERIFIED',
      'forms.account_created': 'ACCOUNT CREATED',
      'forms.account_activated': 'ACCOUNT ACTIVATED',
      'forms.account_deactivated': 'ACCOUNT DEACTIVATED',
      'forms.account_deleted': 'ACCOUNT DELETED',
      'forms.user_created': 'USER CREATED',
      'forms.user_updated': 'USER UPDATED',
      'forms.user_deleted': 'USER DELETED',
      'forms.role_assigned': 'ROLE ASSIGNED',
      'forms.role_removed': 'ROLE REMOVED',
      'forms.permission_granted': 'PERMISSION GRANTED',
      'forms.permission_revoked': 'PERMISSION REVOKED',
      'forms.notification_sent': 'NOTIFICATION SENT',
      'forms.email_sent': 'EMAIL SENT',
      'forms.sms_sent': 'SMS SENT',
      'forms.push_sent': 'PUSH SENT',
      'forms.webhook_sent': 'WEBHOOK SENT',
      'forms.api_key_generated': 'API KEY GENERATED',
      'forms.api_key_revoked': 'API KEY REVOKED',
      'forms.token_generated': 'TOKEN GENERATED',
      'forms.token_revoked': 'TOKEN REVOKED',
      'forms.session_created': 'SESSION CREATED',
      'forms.session_ended': 'SESSION ENDED',
      'forms.log_created': 'LOG CREATED',
      'forms.audit_log_created': 'AUDIT LOG CREATED',
      'forms.error_log_created': 'ERROR LOG CREATED',
      'forms.debug_log_created': 'DEBUG LOG CREATED',
      'forms.info_log_created': 'INFO LOG CREATED',
      'forms.warning_log_created': 'WARNING LOG CREATED',
      'forms.critical_log_created': 'CRITICAL LOG CREATED',
      'forms.emergency_log_created': 'EMERGENCY LOG CREATED',
      'forms.alert_created': 'ALERT CREATED',
      'forms.alert_updated': 'ALERT UPDATED',
      'forms.alert_deleted': 'ALERT DELETED',
      'forms.alert_acknowledged': 'ALERT ACKNOWLEDGED',
      'forms.alert_resolved': 'ALERT RESOLVED',
      'forms.alert_escalated': 'ALERT ESCALATED',
      'forms.threshold_exceeded': 'THRESHOLD EXCEEDED',
      'forms.threshold_breached': 'THRESHOLD BREACHED',
      'forms.threshold_recovered': 'THRESHOLD RECOVERED',
      'forms.sensor_offline': 'SENSOR OFFLINE',
      'forms.sensor_online': 'SENSOR ONLINE',
      'forms.sensor_error': 'SENSOR ERROR',
      'forms.sensor_warning': 'SENSOR WARNING',
      'forms.sensor_critical': 'SENSOR CRITICAL',
      'forms.sensor_normal': 'SENSOR NORMAL',
      'forms.measurement_received': 'MEASUREMENT RECEIVED',
      'forms.measurement_failed': 'MEASUREMENT FAILED',
      'forms.measurement_timeout': 'MEASUREMENT TIMEOUT',
      'forms.measurement_invalid': 'INVALID MEASUREMENT',
      'forms.measurement_outdated': 'OUTDATED MEASUREMENT',
      'forms.measurement_duplicate': 'DUPLICATE MEASUREMENT',
      'forms.measurement_corrupted': 'CORRUPTED MEASUREMENT',
      'forms.measurement_missing': 'MISSING MEASUREMENT',
      'forms.measurement_delayed': 'DELAYED MEASUREMENT',
      'forms.measurement_early': 'EARLY MEASUREMENT',
      'forms.measurement_late': 'LATE MEASUREMENT',
      'forms.measurement_anomaly': 'MEASUREMENT ANOMALY',
      'forms.measurement_spike': 'MEASUREMENT SPIKE',
      'forms.measurement_drop': 'MEASUREMENT DROP',
      'forms.measurement_trend_up': 'UPWARD TREND',
      'forms.measurement_trend_down': 'DOWNWARD TREND',
      'forms.measurement_trend_stable': 'STABLE TREND',
      'forms.measurement_trend_volatile': 'VOLATILE TREND',
      'forms.measurement_trend_cyclical': 'CYCLICAL TREND',
      'forms.measurement_trend_seasonal': 'SEASONAL TREND',
      'forms.measurement_trend_random': 'RANDOM TREND',
      'forms.measurement_trend_linear': 'LINEAR TREND',
      'forms.measurement_trend_exponential': 'EXPONENTIAL TREND',
      'forms.measurement_trend_logarithmic': 'LOGARITHMIC TREND',
      'forms.measurement_trend_polynomial': 'POLYNOMIAL TREND',
      'forms.measurement_trend_sinusoidal': 'SINUSOIDAL TREND',
      'forms.measurement_trend_cosine': 'COSINE TREND',
      'forms.measurement_trend_tangent': 'TANGENT TREND',
      'forms.measurement_trend_hyperbolic': 'HYPERBOLIC TREND',
      'forms.measurement_trend_parabolic': 'PARABOLIC TREND',
      'forms.measurement_trend_cubic': 'CUBIC TREND',
      'forms.measurement_trend_quartic': 'QUARTIC TREND',
      'forms.measurement_trend_quintic': 'QUINTIC TREND',
      'forms.measurement_trend_hexic': 'HEXIC TREND',
      'forms.measurement_trend_heptic': 'HEPTIC TREND',
      'forms.measurement_trend_octic': 'OCTIC TREND',
      'forms.measurement_trend_nonic': 'NONIC TREND',
      'forms.measurement_trend_decic': 'DECIC TREND',
      'forms.measurement_trend_undecic': 'UNDECIC TREND',
      'forms.measurement_trend_dodecic': 'DODECIC TREND',
      'forms.measurement_trend_tridecic': 'TRIDECIC TREND',
      'forms.measurement_trend_tetradecic': 'TETRADECIC TREND',
      'forms.measurement_trend_pentadecic': 'PENTADECIC TREND',
      'forms.measurement_trend_hexadecic': 'HEXADECIC TREND',
      'forms.measurement_trend_heptadecic': 'HEPTADECIC TREND',
      'forms.measurement_trend_octadecic': 'OCTADECIC TREND',
      'forms.measurement_trend_nondecic': 'NONDECIC TREND',
      'forms.measurement_trend_vigintic': 'VIGINTIC TREND',
      'forms.measurement_trend_centic': 'CENTIC TREND',
      'forms.measurement_trend_millic': 'MILLIC TREND',
      'forms.measurement_trend_megic': 'MEGIC TREND',
      'forms.measurement_trend_gigic': 'GIGIC TREND',
      'subtabs.status': 'STATUS',
      'subtabs.insert': 'CREATE',
      'subtabs.update': 'UPDATE',
      'subtabs.massive': 'MASSIVE',
      'subtabs.alerts': 'ALERTS',
      'subtabs.messages': 'MESSAGES',
      'subtabs.dashboard': 'DASHBOARD',
      'fields.country': 'COUNTRY',
      'fields.company': 'COMPANY',
      'fields.fund': 'FUND',
      'fields.location': 'LOCATION',
      'fields.entity': 'ENTITY',
      'fields.node': 'NODE',
      'fields.sensor': 'SENSOR',
      'fields.metric': 'METRIC',
      'fields.type': 'TYPE',
      'fields.measurement': 'MEASUREMENT',
      'fields.threshold': 'THRESHOLD',
      'fields.alert': 'ALERT',
      'fields.user': 'USER',
      'fields.medium': 'MEDIUM',
      'fields.contact': 'CONTACT',
      'fields.localization': 'LOCALIZATION',
      'fields.sensor_metric': 'SENSOR METRIC',
      'fields.threshold_profile': 'THRESHOLD PROFILE',
      'fields.audit_log_threshold': 'AUDIT LOG THRESHOLD',
      'fields.criticality': 'CRITICALITY',
      'fields.name': 'NAME',
      'fields.description': 'DESCRIPTION',
      'fields.value': 'VALUE',
      'fields.min_value': 'MIN VALUE',
      'fields.max_value': 'MAX VALUE',
      'fields.current_value': 'CURRENT VALUE',
      'fields.last_measurement': 'LAST MEASUREMENT',
      'fields.date_created': 'DATE CREATED',
      'fields.date_updated': 'DATE UPDATED',
      'fields.created_by': 'CREATED BY',
      'fields.updated_by': 'UPDATED BY',
      'fields.actions': 'ACTIONS',
      'fields.view': 'VIEW',
      'fields.details': 'DETAILS',
      'fields.settings': 'SETTINGS',
      'fields.profile': 'PROFILE',
      'fields.help': 'HELP',
      'fields.about': 'ABOUT',
      'fields.version': 'VERSION',
      'fields.copyright': 'COPYRIGHT',
      'fields.privacy': 'PRIVACY',
      'fields.terms': 'TERMS',
      'fields.contact_us': 'CONTACT US',
      'fields.support': 'SUPPORT',
      'fields.documentation': 'DOCUMENTATION',
      'fields.api': 'API',
      'fields.export': 'EXPORT',
      'fields.import': 'IMPORT',
      'fields.download': 'DOWNLOAD',
      'fields.upload': 'UPLOAD',
      'fields.refresh': 'REFRESH',
      'fields.reload': 'RELOAD',
      'fields.clear': 'CLEAR',
      'fields.reset_filters': 'RESET FILTERS',
      'fields.apply_filters': 'APPLY FILTERS',
      'fields.no_data': 'NO DATA AVAILABLE',
      'fields.no_results': 'NO RESULTS FOUND',
      'fields.loading_data': 'LOADING DATA...',
      'fields.error_loading': 'ERROR LOADING DATA',
      'fields.connection_error': 'CONNECTION ERROR',
      'fields.server_error': 'SERVER ERROR',
      'fields.network_error': 'NETWORK ERROR',
      'fields.timeout_error': 'TIMEOUT ERROR',
      'fields.unauthorized': 'UNAUTHORIZED',
      'fields.forbidden': 'FORBIDDEN',
      'fields.not_found': 'NOT FOUND',
      'fields.bad_request': 'BAD REQUEST',
      'fields.internal_error': 'INTERNAL ERROR',
      'fields.validation_error': 'VALIDATION ERROR',
      'fields.duplicate_error': 'DUPLICATE ERROR',
      'fields.constraint_error': 'CONSTRAINT ERROR',
      'fields.foreign_key_error': 'FOREIGN KEY ERROR',
      'fields.unique_error': 'UNIQUE ERROR',
      'fields.required_field': 'REQUIRED FIELD',
      'fields.invalid_format': 'INVALID FORMAT',
      'fields.invalid_value': 'INVALID VALUE',
      'fields.min_length': 'MINIMUM LENGTH',
      'fields.max_length': 'MAXIMUM LENGTH',
      'fields.min_value_error': 'MINIMUM VALUE',
      'fields.max_value_error': 'MAXIMUM VALUE',
      'fields.email_invalid': 'INVALID EMAIL',
      'fields.password_weak': 'WEAK PASSWORD',
      'fields.password_mismatch': 'PASSWORDS DO NOT MATCH',
      'fields.username_taken': 'USERNAME ALREADY EXISTS',
      'fields.email_taken': 'EMAIL ALREADY EXISTS',
      'fields.account_locked': 'ACCOUNT LOCKED',
      'fields.account_disabled': 'ACCOUNT DISABLED',
      'fields.session_expired': 'SESSION EXPIRED',
      'fields.login_required': 'LOGIN REQUIRED',
      'fields.permission_denied': 'PERMISSION DENIED',
      'fields.access_denied': 'ACCESS DENIED',
      'fields.operation_successful': 'OPERATION SUCCESSFUL',
      'fields.operation_failed': 'OPERATION FAILED',
      'fields.changes_saved': 'CHANGES SAVED',
      'fields.changes_discarded': 'CHANGES DISCARDED',
      'fields.data_updated': 'DATA UPDATED',
      'fields.data_created': 'DATA CREATED',
      'fields.data_deleted': 'DATA DELETED',
      'fields.data_restored': 'DATA RESTORED',
      'fields.backup_created': 'BACKUP CREATED',
      'fields.backup_restored': 'BACKUP RESTORED',
      'fields.settings_updated': 'SETTINGS UPDATED',
      'fields.profile_updated': 'PROFILE UPDATED',
      'fields.password_changed': 'PASSWORD CHANGED',
      'fields.email_verified': 'EMAIL VERIFIED',
      'fields.account_created': 'ACCOUNT CREATED',
      'fields.account_activated': 'ACCOUNT ACTIVATED',
      'fields.account_deactivated': 'ACCOUNT DEACTIVATED',
      'fields.account_deleted': 'ACCOUNT DELETED',
      'fields.user_created': 'USER CREATED',
      'fields.user_updated': 'USER UPDATED',
      'fields.user_deleted': 'USER DELETED',
      'fields.role_assigned': 'ROLE ASSIGNED',
      'fields.role_removed': 'ROLE REMOVED',
      'fields.permission_granted': 'PERMISSION GRANTED',
      'fields.permission_revoked': 'PERMISSION REVOKED',
      'fields.notification_sent': 'NOTIFICATION SENT',
      'fields.email_sent': 'EMAIL SENT',
      'fields.sms_sent': 'SMS SENT',
      'fields.push_sent': 'PUSH SENT',
      'fields.webhook_sent': 'WEBHOOK SENT',
      'fields.api_key_generated': 'API KEY GENERATED',
      'fields.api_key_revoked': 'API KEY REVOKED',
      'fields.token_generated': 'TOKEN GENERATED',
      'fields.token_revoked': 'TOKEN REVOKED',
      'fields.session_created': 'SESSION CREATED',
      'fields.session_ended': 'SESSION ENDED',
      'fields.log_created': 'LOG CREATED',
      'fields.audit_log_created': 'AUDIT LOG CREATED',
      'fields.error_log_created': 'ERROR LOG CREATED',
      'fields.debug_log_created': 'DEBUG LOG CREATED',
      'fields.info_log_created': 'INFO LOG CREATED',
      'fields.warning_log_created': 'WARNING LOG CREATED',
      'fields.critical_log_created': 'CRITICAL LOG CREATED',
      'fields.emergency_log_created': 'EMERGENCY LOG CREATED',
      'fields.alert_created': 'ALERT CREATED',
      'fields.alert_updated': 'ALERT UPDATED',
      'fields.alert_deleted': 'ALERT DELETED',
      'fields.alert_acknowledged': 'ALERT ACKNOWLEDGED',
      'fields.alert_resolved': 'ALERT RESOLVED',
      'fields.alert_escalated': 'ALERT ESCALATED',
      'fields.threshold_exceeded': 'THRESHOLD EXCEEDED',
      'fields.threshold_breached': 'THRESHOLD BREACHED',
      'fields.threshold_recovered': 'THRESHOLD RECOVERED',
      'fields.sensor_offline': 'SENSOR OFFLINE',
      'fields.sensor_online': 'SENSOR ONLINE',
      'fields.sensor_error': 'SENSOR ERROR',
      'fields.sensor_warning': 'SENSOR WARNING',
      'fields.sensor_critical': 'SENSOR CRITICAL',
      'fields.sensor_normal': 'SENSOR NORMAL',
      'fields.measurement_received': 'MEASUREMENT RECEIVED',
      'fields.measurement_failed': 'MEASUREMENT FAILED',
      'fields.measurement_timeout': 'MEASUREMENT TIMEOUT',
      'fields.measurement_invalid': 'INVALID MEASUREMENT',
      'fields.measurement_outdated': 'OUTDATED MEASUREMENT',
      'fields.measurement_duplicate': 'DUPLICATE MEASUREMENT',
      'fields.measurement_corrupted': 'CORRUPTED MEASUREMENT',
      'fields.measurement_missing': 'MISSING MEASUREMENT',
      'fields.measurement_delayed': 'DELAYED MEASUREMENT',
      'fields.measurement_early': 'EARLY MEASUREMENT',
      'fields.measurement_late': 'LATE MEASUREMENT',
      'fields.measurement_anomaly': 'MEASUREMENT ANOMALY',
      'fields.measurement_spike': 'MEASUREMENT SPIKE',
      'fields.measurement_drop': 'MEASUREMENT DROP',
      'fields.measurement_trend_up': 'UPWARD TREND',
      'fields.measurement_trend_down': 'DOWNWARD TREND',
      'fields.measurement_trend_stable': 'STABLE TREND',
      'fields.measurement_trend_volatile': 'VOLATILE TREND',
      'fields.measurement_trend_cyclical': 'CYCLICAL TREND',
      'fields.measurement_trend_seasonal': 'SEASONAL TREND',
      'fields.measurement_trend_random': 'RANDOM TREND',
      'fields.measurement_trend_linear': 'LINEAR TREND',
      'fields.measurement_trend_exponential': 'EXPONENTIAL TREND',
      'fields.measurement_trend_logarithmic': 'LOGARITHMIC TREND',
      'fields.measurement_trend_polynomial': 'POLYNOMIAL TREND',
      'fields.measurement_trend_sinusoidal': 'SINUSOIDAL TREND',
      'fields.measurement_trend_cosine': 'COSINE TREND',
      'fields.measurement_trend_tangent': 'TANGENT TREND',
      'fields.measurement_trend_hyperbolic': 'HYPERBOLIC TREND',
      'fields.measurement_trend_parabolic': 'PARABOLIC TREND',
      'fields.measurement_trend_cubic': 'CUBIC TREND',
      'fields.measurement_trend_quartic': 'QUARTIC TREND',
      'fields.measurement_trend_quintic': 'QUINTIC TREND',
      'fields.measurement_trend_hexic': 'HEXIC TREND',
      'fields.measurement_trend_heptic': 'HEPTIC TREND',
      'fields.measurement_trend_octic': 'OCTIC TREND',
      'fields.measurement_trend_nonic': 'NONIC TREND',
      'fields.measurement_trend_decic': 'DECIC TREND',
      'fields.measurement_trend_undecic': 'UNDECIC TREND',
      'fields.measurement_trend_dodecic': 'DODECIC TREND',
      'fields.measurement_trend_tridecic': 'TRIDECIC TREND',
      'fields.measurement_trend_tetradecic': 'TETRADECIC TREND',
      'fields.measurement_trend_pentadecic': 'PENTADECIC TREND',
      'fields.measurement_trend_hexadecic': 'HEXADECIC TREND',
      'fields.measurement_trend_heptadecic': 'HEPTADECIC TREND',
      'fields.measurement_trend_octadecic': 'OCTADECIC TREND',
      'fields.measurement_trend_nondecic': 'NONDECIC TREND',
      'fields.measurement_trend_vigintic': 'VIGINTIC TREND',
      'fields.measurement_trend_centic': 'CENTIC TREND',
      'fields.measurement_trend_millic': 'MILLIC TREND',
      'fields.measurement_trend_megic': 'MEGIC TREND',
      'fields.measurement_trend_gigic': 'GIGIC TREND'
    }
  };

  const t = (key: string): string => {
    return translations[language]?.[key] || key;
  };

  const handleSetLanguage = (lang: string) => {
    setLanguage(lang);
    // Save to localStorage
    if (typeof window !== 'undefined') {
      localStorage.setItem('language', lang);
    }
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage: handleSetLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = (): LanguageContextType => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
