import React, { createContext, useContext, useState, ReactNode } from 'react';

interface LanguageContextType {
  language: string;
  setLanguage: (lang: string) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

interface LanguageProviderProps {
  children: ReactNode;
}

export const LanguageProvider: React.FC<LanguageProviderProps> = ({ children }) => {
  const [language, setLanguage] = useState<string>('es');

  const translations: Record<string, Record<string, string>> = {
    es: {
      'welcome.title': 'Bienvenido a JoySense Dashboard',
      'welcome.subtitle': 'Sistema de Monitoreo Inteligente',
      'dashboard.title': 'Dashboard',
      'parameters.title': 'Parámetros',
      'reports.title': 'Reportes',
      'alerts.title': 'Alertas',
      'messages.title': 'Mensajes',
      'login.title': 'Iniciar Sesión',
      'login.subtitle': 'Accede a tu cuenta',
      'login.email': 'Correo Electrónico',
      'login.password': 'Contraseña',
      'login.button': 'Iniciar Sesión',
      'login.error': 'Credenciales inválidas',
      'logout.button': 'Cerrar Sesión',
      'loading': 'Cargando...',
      'error': 'Error',
      'success': 'Éxito',
      'warning': 'Advertencia',
      'info': 'Información',
      'save': 'Guardar',
      'cancel': 'Cancelar',
      'delete': 'Eliminar',
      'edit': 'Editar',
      'create': 'Crear',
      'update': 'Actualizar',
      'search': 'Buscar',
      'filter': 'Filtrar',
      'reset': 'Restablecer',
      'confirm': 'Confirmar',
      'yes': 'Sí',
      'no': 'No',
      'close': 'Cerrar',
      'back': 'Volver',
      'next': 'Siguiente',
      'previous': 'Anterior',
      'select': 'Seleccionar',
      'all': 'Todos',
      'none': 'Ninguno',
      'status': 'Estado',
      'active': 'Activo',
      'inactive': 'Inactivo',
      'enabled': 'Habilitado',
      'disabled': 'Deshabilitado',
      'country': 'País',
      'company': 'Empresa',
      'fund': 'Fundo',
      'location': 'Ubicación',
      'entity': 'Entidad',
      'node': 'Nodo',
      'sensor': 'Sensor',
      'metric': 'Métrica',
      'type': 'Tipo',
      'measurement': 'Medición',
      'threshold': 'Umbral',
      'alert': 'Alerta',
      'user': 'Usuario',
      'medium': 'Medio',
      'contact': 'Contacto',
      'localization': 'Localización',
      'sensor_metric': 'Métrica Sensor',
      'threshold_profile': 'Perfil Umbral',
      'audit_log_threshold': 'Audit Log Umbral',
      'criticality': 'Criticidad',
      'name': 'Nombre',
      'description': 'Descripción',
      'value': 'Valor',
      'min_value': 'Valor Mínimo',
      'max_value': 'Valor Máximo',
      'current_value': 'Valor Actual',
      'last_measurement': 'Última Medición',
      'date_created': 'Fecha de Creación',
      'date_updated': 'Fecha de Actualización',
      'created_by': 'Creado por',
      'updated_by': 'Actualizado por',
      'actions': 'Acciones',
      'view': 'Ver',
      'details': 'Detalles',
      'settings': 'Configuración',
      'profile': 'Perfil',
      'help': 'Ayuda',
      'about': 'Acerca de',
      'version': 'Versión',
      'copyright': 'Derechos de Autor',
      'privacy': 'Privacidad',
      'terms': 'Términos',
      'contact_us': 'Contáctanos',
      'support': 'Soporte',
      'documentation': 'Documentación',
      'api': 'API',
      'export': 'Exportar',
      'import': 'Importar',
      'download': 'Descargar',
      'upload': 'Subir',
      'refresh': 'Actualizar',
      'reload': 'Recargar',
      'clear': 'Limpiar',
      'reset_filters': 'Restablecer Filtros',
      'apply_filters': 'Aplicar Filtros',
      'no_data': 'No hay datos disponibles',
      'no_results': 'No se encontraron resultados',
      'loading_data': 'Cargando datos...',
      'error_loading': 'Error al cargar los datos',
      'connection_error': 'Error de conexión',
      'server_error': 'Error del servidor',
      'network_error': 'Error de red',
      'timeout_error': 'Error de tiempo de espera',
      'unauthorized': 'No autorizado',
      'forbidden': 'Prohibido',
      'not_found': 'No encontrado',
      'bad_request': 'Solicitud incorrecta',
      'internal_error': 'Error interno',
      'validation_error': 'Error de validación',
      'duplicate_error': 'Error de duplicado',
      'constraint_error': 'Error de restricción',
      'foreign_key_error': 'Error de clave foránea',
      'unique_error': 'Error de unicidad',
      'required_field': 'Campo requerido',
      'invalid_format': 'Formato inválido',
      'invalid_value': 'Valor inválido',
      'min_length': 'Longitud mínima',
      'max_length': 'Longitud máxima',
      'min_value_error': 'Valor mínimo',
      'max_value_error': 'Valor máximo',
      'email_invalid': 'Correo electrónico inválido',
      'password_weak': 'Contraseña débil',
      'password_mismatch': 'Las contraseñas no coinciden',
      'username_taken': 'Nombre de usuario ya existe',
      'email_taken': 'Correo electrónico ya existe',
      'account_locked': 'Cuenta bloqueada',
      'account_disabled': 'Cuenta deshabilitada',
      'session_expired': 'Sesión expirada',
      'login_required': 'Inicio de sesión requerido',
      'permission_denied': 'Permiso denegado',
      'access_denied': 'Acceso denegado',
      'operation_successful': 'Operación exitosa',
      'operation_failed': 'Operación fallida',
      'changes_saved': 'Cambios guardados',
      'changes_discarded': 'Cambios descartados',
      'data_updated': 'Datos actualizados',
      'data_created': 'Datos creados',
      'data_deleted': 'Datos eliminados',
      'data_restored': 'Datos restaurados',
      'backup_created': 'Respaldo creado',
      'backup_restored': 'Respaldo restaurado',
      'settings_updated': 'Configuración actualizada',
      'profile_updated': 'Perfil actualizado',
      'password_changed': 'Contraseña cambiada',
      'email_verified': 'Correo electrónico verificado',
      'account_created': 'Cuenta creada',
      'account_activated': 'Cuenta activada',
      'account_deactivated': 'Cuenta desactivada',
      'account_deleted': 'Cuenta eliminada',
      'user_created': 'Usuario creado',
      'user_updated': 'Usuario actualizado',
      'user_deleted': 'Usuario eliminado',
      'role_assigned': 'Rol asignado',
      'role_removed': 'Rol removido',
      'permission_granted': 'Permiso otorgado',
      'permission_revoked': 'Permiso revocado',
      'notification_sent': 'Notificación enviada',
      'email_sent': 'Correo enviado',
      'sms_sent': 'SMS enviado',
      'push_sent': 'Push enviado',
      'webhook_sent': 'Webhook enviado',
      'api_key_generated': 'Clave API generada',
      'api_key_revoked': 'Clave API revocada',
      'token_generated': 'Token generado',
      'token_revoked': 'Token revocado',
      'session_created': 'Sesión creada',
      'session_ended': 'Sesión terminada',
      'log_created': 'Log creado',
      'audit_log_created': 'Log de auditoría creado',
      'error_log_created': 'Log de error creado',
      'debug_log_created': 'Log de depuración creado',
      'info_log_created': 'Log de información creado',
      'warning_log_created': 'Log de advertencia creado',
      'critical_log_created': 'Log crítico creado',
      'emergency_log_created': 'Log de emergencia creado',
      'alert_created': 'Alerta creada',
      'alert_updated': 'Alerta actualizada',
      'alert_deleted': 'Alerta eliminada',
      'alert_acknowledged': 'Alerta reconocida',
      'alert_resolved': 'Alerta resuelta',
      'alert_escalated': 'Alerta escalada',
      'threshold_exceeded': 'Umbral excedido',
      'threshold_breached': 'Umbral violado',
      'threshold_recovered': 'Umbral recuperado',
      'sensor_offline': 'Sensor fuera de línea',
      'sensor_online': 'Sensor en línea',
      'sensor_error': 'Error del sensor',
      'sensor_warning': 'Advertencia del sensor',
      'sensor_critical': 'Sensor crítico',
      'sensor_normal': 'Sensor normal',
      'measurement_received': 'Medición recibida',
      'measurement_failed': 'Medición fallida',
      'measurement_timeout': 'Medición con tiempo de espera',
      'measurement_invalid': 'Medición inválida',
      'measurement_outdated': 'Medición desactualizada',
      'measurement_duplicate': 'Medición duplicada',
      'measurement_corrupted': 'Medición corrupta',
      'measurement_missing': 'Medición faltante',
      'measurement_delayed': 'Medición retrasada',
      'measurement_early': 'Medición temprana',
      'measurement_late': 'Medición tardía',
      'measurement_anomaly': 'Anomalía en medición',
      'measurement_spike': 'Pico en medición',
      'measurement_drop': 'Caída en medición',
      'measurement_trend_up': 'Tendencia ascendente',
      'measurement_trend_down': 'Tendencia descendente',
      'measurement_trend_stable': 'Tendencia estable',
      'measurement_trend_volatile': 'Tendencia volátil',
      'measurement_trend_cyclical': 'Tendencia cíclica',
      'measurement_trend_seasonal': 'Tendencia estacional',
      'measurement_trend_random': 'Tendencia aleatoria',
      'measurement_trend_linear': 'Tendencia lineal',
      'measurement_trend_exponential': 'Tendencia exponencial',
      'measurement_trend_logarithmic': 'Tendencia logarítmica',
      'measurement_trend_polynomial': 'Tendencia polinomial',
      'measurement_trend_sinusoidal': 'Tendencia sinusoidal',
      'measurement_trend_cosine': 'Tendencia coseno',
      'measurement_trend_tangent': 'Tendencia tangente',
      'measurement_trend_hyperbolic': 'Tendencia hiperbólica',
      'measurement_trend_parabolic': 'Tendencia parabólica',
      'measurement_trend_cubic': 'Tendencia cúbica',
      'measurement_trend_quartic': 'Tendencia cuártica',
      'measurement_trend_quintic': 'Tendencia quíntica',
      'measurement_trend_hexic': 'Tendencia séxtica',
      'measurement_trend_heptic': 'Tendencia séptica',
      'measurement_trend_octic': 'Tendencia óctica',
      'measurement_trend_nonic': 'Tendencia nónica',
      'measurement_trend_decic': 'Tendencia décica',
      'measurement_trend_undecic': 'Tendencia undécica',
      'measurement_trend_dodecic': 'Tendencia dodecica',
      'measurement_trend_tridecic': 'Tendencia tridecica',
      'measurement_trend_tetradecic': 'Tendencia tetradecica',
      'measurement_trend_pentadecic': 'Tendencia pentadecica',
      'measurement_trend_hexadecic': 'Tendencia hexadecica',
      'measurement_trend_heptadecic': 'Tendencia heptadecica',
      'measurement_trend_octadecic': 'Tendencia octadecica',
      'measurement_trend_nondecic': 'Tendencia nondecica',
      'measurement_trend_vigintic': 'Tendencia vigintica',
      'measurement_trend_centic': 'Tendencia centica',
      'measurement_trend_millic': 'Tendencia millica',
      'measurement_trend_megic': 'Tendencia megica',
      'measurement_trend_gigic': 'Tendencia gigica',
    },
    en: {
      'welcome.title': 'Welcome to JoySense Dashboard',
      'welcome.subtitle': 'Intelligent Monitoring System',
      'dashboard.title': 'Dashboard',
      'parameters.title': 'Parameters',
      'reports.title': 'Reports',
      'alerts.title': 'Alerts',
      'messages.title': 'Messages',
      'login.title': 'Sign In',
      'login.subtitle': 'Access your account',
      'login.email': 'Email',
      'login.password': 'Password',
      'login.button': 'Sign In',
      'login.error': 'Invalid credentials',
      'logout.button': 'Sign Out',
      'loading': 'Loading...',
      'error': 'Error',
      'success': 'Success',
      'warning': 'Warning',
      'info': 'Information',
      'save': 'Save',
      'cancel': 'Cancel',
      'delete': 'Delete',
      'edit': 'Edit',
      'create': 'Create',
      'update': 'Update',
      'search': 'Search',
      'filter': 'Filter',
      'reset': 'Reset',
      'confirm': 'Confirm',
      'yes': 'Yes',
      'no': 'No',
      'close': 'Close',
      'back': 'Back',
      'next': 'Next',
      'previous': 'Previous',
      'select': 'Select',
      'all': 'All',
      'none': 'None',
      'status': 'Status',
      'active': 'Active',
      'inactive': 'Inactive',
      'enabled': 'Enabled',
      'disabled': 'Disabled',
      'country': 'Country',
      'company': 'Company',
      'fund': 'Fund',
      'location': 'Location',
      'entity': 'Entity',
      'node': 'Node',
      'sensor': 'Sensor',
      'metric': 'Metric',
      'type': 'Type',
      'measurement': 'Measurement',
      'threshold': 'Threshold',
      'alert': 'Alert',
      'user': 'User',
      'medium': 'Medium',
      'contact': 'Contact',
      'localization': 'Localization',
      'sensor_metric': 'Sensor Metric',
      'threshold_profile': 'Threshold Profile',
      'audit_log_threshold': 'Audit Log Threshold',
      'criticality': 'Criticality',
      'name': 'Name',
      'description': 'Description',
      'value': 'Value',
      'min_value': 'Min Value',
      'max_value': 'Max Value',
      'current_value': 'Current Value',
      'last_measurement': 'Last Measurement',
      'date_created': 'Date Created',
      'date_updated': 'Date Updated',
      'created_by': 'Created By',
      'updated_by': 'Updated By',
      'actions': 'Actions',
      'view': 'View',
      'details': 'Details',
      'settings': 'Settings',
      'profile': 'Profile',
      'help': 'Help',
      'about': 'About',
      'version': 'Version',
      'copyright': 'Copyright',
      'privacy': 'Privacy',
      'terms': 'Terms',
      'contact_us': 'Contact Us',
      'support': 'Support',
      'documentation': 'Documentation',
      'api': 'API',
      'export': 'Export',
      'import': 'Import',
      'download': 'Download',
      'upload': 'Upload',
      'refresh': 'Refresh',
      'reload': 'Reload',
      'clear': 'Clear',
      'reset_filters': 'Reset Filters',
      'apply_filters': 'Apply Filters',
      'no_data': 'No data available',
      'no_results': 'No results found',
      'loading_data': 'Loading data...',
      'error_loading': 'Error loading data',
      'connection_error': 'Connection error',
      'server_error': 'Server error',
      'network_error': 'Network error',
      'timeout_error': 'Timeout error',
      'unauthorized': 'Unauthorized',
      'forbidden': 'Forbidden',
      'not_found': 'Not found',
      'bad_request': 'Bad request',
      'internal_error': 'Internal error',
      'validation_error': 'Validation error',
      'duplicate_error': 'Duplicate error',
      'constraint_error': 'Constraint error',
      'foreign_key_error': 'Foreign key error',
      'unique_error': 'Unique error',
      'required_field': 'Required field',
      'invalid_format': 'Invalid format',
      'invalid_value': 'Invalid value',
      'min_length': 'Minimum length',
      'max_length': 'Maximum length',
      'min_value_error': 'Minimum value',
      'max_value_error': 'Maximum value',
      'email_invalid': 'Invalid email',
      'password_weak': 'Weak password',
      'password_mismatch': 'Passwords do not match',
      'username_taken': 'Username already exists',
      'email_taken': 'Email already exists',
      'account_locked': 'Account locked',
      'account_disabled': 'Account disabled',
      'session_expired': 'Session expired',
      'login_required': 'Login required',
      'permission_denied': 'Permission denied',
      'access_denied': 'Access denied',
      'operation_successful': 'Operation successful',
      'operation_failed': 'Operation failed',
      'changes_saved': 'Changes saved',
      'changes_discarded': 'Changes discarded',
      'data_updated': 'Data updated',
      'data_created': 'Data created',
      'data_deleted': 'Data deleted',
      'data_restored': 'Data restored',
      'backup_created': 'Backup created',
      'backup_restored': 'Backup restored',
      'settings_updated': 'Settings updated',
      'profile_updated': 'Profile updated',
      'password_changed': 'Password changed',
      'email_verified': 'Email verified',
      'account_created': 'Account created',
      'account_activated': 'Account activated',
      'account_deactivated': 'Account deactivated',
      'account_deleted': 'Account deleted',
      'user_created': 'User created',
      'user_updated': 'User updated',
      'user_deleted': 'User deleted',
      'role_assigned': 'Role assigned',
      'role_removed': 'Role removed',
      'permission_granted': 'Permission granted',
      'permission_revoked': 'Permission revoked',
      'notification_sent': 'Notification sent',
      'email_sent': 'Email sent',
      'sms_sent': 'SMS sent',
      'push_sent': 'Push sent',
      'webhook_sent': 'Webhook sent',
      'api_key_generated': 'API key generated',
      'api_key_revoked': 'API key revoked',
      'token_generated': 'Token generated',
      'token_revoked': 'Token revoked',
      'session_created': 'Session created',
      'session_ended': 'Session ended',
      'log_created': 'Log created',
      'audit_log_created': 'Audit log created',
      'error_log_created': 'Error log created',
      'debug_log_created': 'Debug log created',
      'info_log_created': 'Info log created',
      'warning_log_created': 'Warning log created',
      'critical_log_created': 'Critical log created',
      'emergency_log_created': 'Emergency log created',
      'alert_created': 'Alert created',
      'alert_updated': 'Alert updated',
      'alert_deleted': 'Alert deleted',
      'alert_acknowledged': 'Alert acknowledged',
      'alert_resolved': 'Alert resolved',
      'alert_escalated': 'Alert escalated',
      'threshold_exceeded': 'Threshold exceeded',
      'threshold_breached': 'Threshold breached',
      'threshold_recovered': 'Threshold recovered',
      'sensor_offline': 'Sensor offline',
      'sensor_online': 'Sensor online',
      'sensor_error': 'Sensor error',
      'sensor_warning': 'Sensor warning',
      'sensor_critical': 'Sensor critical',
      'sensor_normal': 'Sensor normal',
      'measurement_received': 'Measurement received',
      'measurement_failed': 'Measurement failed',
      'measurement_timeout': 'Measurement timeout',
      'measurement_invalid': 'Invalid measurement',
      'measurement_outdated': 'Outdated measurement',
      'measurement_duplicate': 'Duplicate measurement',
      'measurement_corrupted': 'Corrupted measurement',
      'measurement_missing': 'Missing measurement',
      'measurement_delayed': 'Delayed measurement',
      'measurement_early': 'Early measurement',
      'measurement_late': 'Late measurement',
      'measurement_anomaly': 'Measurement anomaly',
      'measurement_spike': 'Measurement spike',
      'measurement_drop': 'Measurement drop',
      'measurement_trend_up': 'Upward trend',
      'measurement_trend_down': 'Downward trend',
      'measurement_trend_stable': 'Stable trend',
      'measurement_trend_volatile': 'Volatile trend',
      'measurement_trend_cyclical': 'Cyclical trend',
      'measurement_trend_seasonal': 'Seasonal trend',
      'measurement_trend_random': 'Random trend',
      'measurement_trend_linear': 'Linear trend',
      'measurement_trend_exponential': 'Exponential trend',
      'measurement_trend_logarithmic': 'Logarithmic trend',
      'measurement_trend_polynomial': 'Polynomial trend',
      'measurement_trend_sinusoidal': 'Sinusoidal trend',
      'measurement_trend_cosine': 'Cosine trend',
      'measurement_trend_tangent': 'Tangent trend',
      'measurement_trend_hyperbolic': 'Hyperbolic trend',
      'measurement_trend_parabolic': 'Parabolic trend',
      'measurement_trend_cubic': 'Cubic trend',
      'measurement_trend_quartic': 'Quartic trend',
      'measurement_trend_quintic': 'Quintic trend',
      'measurement_trend_hexic': 'Hexic trend',
      'measurement_trend_heptic': 'Heptic trend',
      'measurement_trend_octic': 'Octic trend',
      'measurement_trend_nonic': 'Nonic trend',
      'measurement_trend_decic': 'Decic trend',
      'measurement_trend_undecic': 'Undecic trend',
      'measurement_trend_dodecic': 'Dodecic trend',
      'measurement_trend_tridecic': 'Tridecic trend',
      'measurement_trend_tetradecic': 'Tetradecic trend',
      'measurement_trend_pentadecic': 'Pentadecic trend',
      'measurement_trend_hexadecic': 'Hexadecic trend',
      'measurement_trend_heptadecic': 'Heptadecic trend',
      'measurement_trend_octadecic': 'Octadecic trend',
      'measurement_trend_nondecic': 'Nondecic trend',
      'measurement_trend_vigintic': 'Vigintic trend',
      'measurement_trend_centic': 'Centic trend',
      'measurement_trend_millic': 'Millic trend',
      'measurement_trend_megic': 'Megic trend',
      'measurement_trend_gigic': 'Gigic trend',
      'measurement_trend_teric': 'Teric trend',
      'measurement_trend_petic': 'Petic trend',
      'measurement_trend_exic': 'Exic trend',
      'measurement_trend_zetic': 'Zetic trend',
      'measurement_trend_yotic': 'Yotic trend',
      'measurement_trend_ronnic': 'Ronnic trend',
      'measurement_trend_quetic': 'Quetic trend'
    }
  };

  const t = (key: string): string => {
    return translations[language]?.[key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = (): LanguageContextType => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
