-- Script completo para traducir todos los países del CSV al español
-- Basado en country_dial_codes.csv

-- Países de América Latina
UPDATE sense.codigotelefono SET paistelefono = 'Perú' WHERE codigotelefono = '+51' AND paistelefono = 'Peru';
UPDATE sense.codigotelefono SET paistelefono = 'México' WHERE codigotelefono = '+52' AND paistelefono = 'Mexico';
UPDATE sense.codigotelefono SET paistelefono = 'Colombia' WHERE codigotelefono = '+57' AND paistelefono = 'Colombia';
UPDATE sense.codigotelefono SET paistelefono = 'Venezuela' WHERE codigotelefono = '+58' AND paistelefono = 'Venezuela';
UPDATE sense.codigotelefono SET paistelefono = 'Argentina' WHERE codigotelefono = '+54' AND paistelefono = 'Argentina';
UPDATE sense.codigotelefono SET paistelefono = 'Chile' WHERE codigotelefono = '+56' AND paistelefono = 'Chile';
UPDATE sense.codigotelefono SET paistelefono = 'Ecuador' WHERE codigotelefono = '+593' AND paistelefono = 'Ecuador';
UPDATE sense.codigotelefono SET paistelefono = 'Bolivia' WHERE codigotelefono = '+591' AND paistelefono = 'Bolivia';
UPDATE sense.codigotelefono SET paistelefono = 'Paraguay' WHERE codigotelefono = '+595' AND paistelefono = 'Paraguay';
UPDATE sense.codigotelefono SET paistelefono = 'Uruguay' WHERE codigotelefono = '+598' AND paistelefono = 'Uruguay';
UPDATE sense.codigotelefono SET paistelefono = 'Brasil' WHERE codigotelefono = '+55' AND paistelefono = 'Brazil';
UPDATE sense.codigotelefono SET paistelefono = 'Guatemala' WHERE codigotelefono = '+502' AND paistelefono = 'Guatemala';
UPDATE sense.codigotelefono SET paistelefono = 'Cuba' WHERE codigotelefono = '+53' AND paistelefono = 'Cuba';
UPDATE sense.codigotelefono SET paistelefono = 'Haití' WHERE codigotelefono = '+509' AND paistelefono = 'Haiti';
UPDATE sense.codigotelefono SET paistelefono = 'República Dominicana' WHERE codigotelefono = '+1 809' AND paistelefono = 'Dominican Republic';
UPDATE sense.codigotelefono SET paistelefono = 'Honduras' WHERE codigotelefono = '+504' AND paistelefono = 'Honduras';
UPDATE sense.codigotelefono SET paistelefono = 'Nicaragua' WHERE codigotelefono = '+505' AND paistelefono = 'Nicaragua';
UPDATE sense.codigotelefono SET paistelefono = 'El Salvador' WHERE codigotelefono = '+503' AND paistelefono = 'El Salvador';
UPDATE sense.codigotelefono SET paistelefono = 'Costa Rica' WHERE codigotelefono = '+506' AND paistelefono = 'Costa Rica';
UPDATE sense.codigotelefono SET paistelefono = 'Panamá' WHERE codigotelefono = '+507' AND paistelefono = 'Panama';

-- Países de Europa
UPDATE sense.codigotelefono SET paistelefono = 'España' WHERE codigotelefono = '+34' AND paistelefono = 'Spain';
UPDATE sense.codigotelefono SET paistelefono = 'Francia' WHERE codigotelefono = '+33' AND paistelefono = 'France';
UPDATE sense.codigotelefono SET paistelefono = 'Alemania' WHERE codigotelefono = '+49' AND paistelefono = 'Germany';
UPDATE sense.codigotelefono SET paistelefono = 'Italia' WHERE codigotelefono = '+39' AND paistelefono = 'Italy';
UPDATE sense.codigotelefono SET paistelefono = 'Reino Unido' WHERE codigotelefono = '+44' AND paistelefono = 'United Kingdom';
UPDATE sense.codigotelefono SET paistelefono = 'Portugal' WHERE codigotelefono = '+351' AND paistelefono = 'Portugal';
UPDATE sense.codigotelefono SET paistelefono = 'Países Bajos' WHERE codigotelefono = '+31' AND paistelefono = 'Netherlands';
UPDATE sense.codigotelefono SET paistelefono = 'Bélgica' WHERE codigotelefono = '+32' AND paistelefono = 'Belgium';
UPDATE sense.codigotelefono SET paistelefono = 'Suiza' WHERE codigotelefono = '+41' AND paistelefono = 'Switzerland';
UPDATE sense.codigotelefono SET paistelefono = 'Austria' WHERE codigotelefono = '+43' AND paistelefono = 'Austria';
UPDATE sense.codigotelefono SET paistelefono = 'Rusia' WHERE codigotelefono = '+7' AND paistelefono = 'Russia';
UPDATE sense.codigotelefono SET paistelefono = 'Polonia' WHERE codigotelefono = '+48' AND paistelefono = 'Poland';
UPDATE sense.codigotelefono SET paistelefono = 'República Checa' WHERE codigotelefono = '+420' AND paistelefono = 'Czech Republic';
UPDATE sense.codigotelefono SET paistelefono = 'Rumania' WHERE codigotelefono = '+40' AND paistelefono = 'Romania';
UPDATE sense.codigotelefono SET paistelefono = 'Grecia' WHERE codigotelefono = '+30' AND paistelefono = 'Greece';
UPDATE sense.codigotelefono SET paistelefono = 'Hungría' WHERE codigotelefono = '+36' AND paistelefono = 'Hungary';
UPDATE sense.codigotelefono SET paistelefono = 'Bulgaria' WHERE codigotelefono = '+359' AND paistelefono = 'Bulgaria';
UPDATE sense.codigotelefono SET paistelefono = 'Croacia' WHERE codigotelefono = '+385' AND paistelefono = 'Croatia';
UPDATE sense.codigotelefono SET paistelefono = 'Eslovaquia' WHERE codigotelefono = '+421' AND paistelefono = 'Slovakia';
UPDATE sense.codigotelefono SET paistelefono = 'Eslovenia' WHERE codigotelefono = '+386' AND paistelefono = 'Slovenia';
UPDATE sense.codigotelefono SET paistelefono = 'Estonia' WHERE codigotelefono = '+372' AND paistelefono = 'Estonia';
UPDATE sense.codigotelefono SET paistelefono = 'Letonia' WHERE codigotelefono = '+371' AND paistelefono = 'Latvia';
UPDATE sense.codigotelefono SET paistelefono = 'Lituania' WHERE codigotelefono = '+370' AND paistelefono = 'Lithuania';
UPDATE sense.codigotelefono SET paistelefono = 'Finlandia' WHERE codigotelefono = '+358' AND paistelefono = 'Finland';
UPDATE sense.codigotelefono SET paistelefono = 'Suecia' WHERE codigotelefono = '+46' AND paistelefono = 'Sweden';
UPDATE sense.codigotelefono SET paistelefono = 'Noruega' WHERE codigotelefono = '+47' AND paistelefono = 'Norway';
UPDATE sense.codigotelefono SET paistelefono = 'Dinamarca' WHERE codigotelefono = '+45' AND paistelefono = 'Denmark';
UPDATE sense.codigotelefono SET paistelefono = 'Islandia' WHERE codigotelefono = '+354' AND paistelefono = 'Iceland';
UPDATE sense.codigotelefono SET paistelefono = 'Irlanda' WHERE codigotelefono = '+353' AND paistelefono = 'Ireland';
UPDATE sense.codigotelefono SET paistelefono = 'Luxemburgo' WHERE codigotelefono = '+352' AND paistelefono = 'Luxembourg';
UPDATE sense.codigotelefono SET paistelefono = 'Malta' WHERE codigotelefono = '+356' AND paistelefono = 'Malta';
UPDATE sense.codigotelefono SET paistelefono = 'Chipre' WHERE codigotelefono = '+357' AND paistelefono = 'Cyprus';
UPDATE sense.codigotelefono SET paistelefono = 'Albania' WHERE codigotelefono = '+355' AND paistelefono = 'Albania';
UPDATE sense.codigotelefono SET paistelefono = 'Bosnia y Herzegovina' WHERE codigotelefono = '+387' AND paistelefono = 'Bosnia and Herzegovina';
UPDATE sense.codigotelefono SET paistelefono = 'Serbia' WHERE codigotelefono = '+381' AND paistelefono = 'Serbia';
UPDATE sense.codigotelefono SET paistelefono = 'Montenegro' WHERE codigotelefono = '+382' AND paistelefono = 'Montenegro';
UPDATE sense.codigotelefono SET paistelefono = 'Macedonia del Norte' WHERE codigotelefono = '+389' AND paistelefono = 'Macedonia';
UPDATE sense.codigotelefono SET paistelefono = 'Moldavia' WHERE codigotelefono = '+373' AND paistelefono = 'Moldova';
UPDATE sense.codigotelefono SET paistelefono = 'Bielorrusia' WHERE codigotelefono = '+375' AND paistelefono = 'Belarus';
UPDATE sense.codigotelefono SET paistelefono = 'Ucrania' WHERE codigotelefono = '+380' AND paistelefono = 'Ukraine';
UPDATE sense.codigotelefono SET paistelefono = 'Armenia' WHERE codigotelefono = '+374' AND paistelefono = 'Armenia';
UPDATE sense.codigotelefono SET paistelefono = 'Georgia' WHERE codigotelefono = '+995' AND paistelefono = 'Georgia';
UPDATE sense.codigotelefono SET paistelefono = 'Azerbaiyán' WHERE codigotelefono = '+994' AND paistelefono = 'Azerbaijan';
UPDATE sense.codigotelefono SET paistelefono = 'Kazajistán' WHERE codigotelefono = '+7' AND paistelefono = 'Kazakhstan';
UPDATE sense.codigotelefono SET paistelefono = 'Uzbekistán' WHERE codigotelefono = '+998' AND paistelefono = 'Uzbekistan';
UPDATE sense.codigotelefono SET paistelefono = 'Kirguistán' WHERE codigotelefono = '+996' AND paistelefono = 'Kyrgyzstan';
UPDATE sense.codigotelefono SET paistelefono = 'Tayikistán' WHERE codigotelefono = '+992' AND paistelefono = 'Tajikistan';
UPDATE sense.codigotelefono SET paistelefono = 'Turkmenistán' WHERE codigotelefono = '+993' AND paistelefono = 'Turkmenistan';
UPDATE sense.codigotelefono SET paistelefono = 'Andorra' WHERE codigotelefono = '+376' AND paistelefono = 'Andorra';
UPDATE sense.codigotelefono SET paistelefono = 'Liechtenstein' WHERE codigotelefono = '+423' AND paistelefono = 'Liechtenstein';
UPDATE sense.codigotelefono SET paistelefono = 'Mónaco' WHERE codigotelefono = '+377' AND paistelefono = 'Monaco';
UPDATE sense.codigotelefono SET paistelefono = 'San Marino' WHERE codigotelefono = '+378' AND paistelefono = 'San Marino';
UPDATE sense.codigotelefono SET paistelefono = 'Ciudad del Vaticano' WHERE codigotelefono = '+379' AND paistelefono = 'Vatican';

-- Países de América del Norte
UPDATE sense.codigotelefono SET paistelefono = 'Estados Unidos' WHERE codigotelefono = '+1' AND paistelefono = 'United States';
UPDATE sense.codigotelefono SET paistelefono = 'Canadá' WHERE codigotelefono = '+1' AND paistelefono = 'Canada';

-- Países de Asia
UPDATE sense.codigotelefono SET paistelefono = 'China' WHERE codigotelefono = '+86' AND paistelefono = 'China';
UPDATE sense.codigotelefono SET paistelefono = 'Japón' WHERE codigotelefono = '+81' AND paistelefono = 'Japan';
UPDATE sense.codigotelefono SET paistelefono = 'Corea del Sur' WHERE codigotelefono = '+82' AND paistelefono = 'South Korea';
UPDATE sense.codigotelefono SET paistelefono = 'Corea del Norte' WHERE codigotelefono = '+850' AND paistelefono = 'North Korea';
UPDATE sense.codigotelefono SET paistelefono = 'India' WHERE codigotelefono = '+91' AND paistelefono = 'India';
UPDATE sense.codigotelefono SET paistelefono = 'Tailandia' WHERE codigotelefono = '+66' AND paistelefono = 'Thailand';
UPDATE sense.codigotelefono SET paistelefono = 'Singapur' WHERE codigotelefono = '+65' AND paistelefono = 'Singapore';
UPDATE sense.codigotelefono SET paistelefono = 'Malasia' WHERE codigotelefono = '+60' AND paistelefono = 'Malaysia';
UPDATE sense.codigotelefono SET paistelefono = 'Filipinas' WHERE codigotelefono = '+63' AND paistelefono = 'Philippines';
UPDATE sense.codigotelefono SET paistelefono = 'Indonesia' WHERE codigotelefono = '+62' AND paistelefono = 'Indonesia';
UPDATE sense.codigotelefono SET paistelefono = 'Vietnam' WHERE codigotelefono = '+84' AND paistelefono = 'Vietnam';
UPDATE sense.codigotelefono SET paistelefono = 'Camboya' WHERE codigotelefono = '+855' AND paistelefono = 'Cambodia';
UPDATE sense.codigotelefono SET paistelefono = 'Laos' WHERE codigotelefono = '+856' AND paistelefono = 'Laos';
UPDATE sense.codigotelefono SET paistelefono = 'Myanmar' WHERE codigotelefono = '+95' AND paistelefono = 'Myanmar';
UPDATE sense.codigotelefono SET paistelefono = 'Bangladesh' WHERE codigotelefono = '+880' AND paistelefono = 'Bangladesh';
UPDATE sense.codigotelefono SET paistelefono = 'Pakistán' WHERE codigotelefono = '+92' AND paistelefono = 'Pakistan';
UPDATE sense.codigotelefono SET paistelefono = 'Sri Lanka' WHERE codigotelefono = '+94' AND paistelefono = 'Sri Lanka';
UPDATE sense.codigotelefono SET paistelefono = 'Maldivas' WHERE codigotelefono = '+960' AND paistelefono = 'Maldives';
UPDATE sense.codigotelefono SET paistelefono = 'Nepal' WHERE codigotelefono = '+977' AND paistelefono = 'Nepal';
UPDATE sense.codigotelefono SET paistelefono = 'Bután' WHERE codigotelefono = '+975' AND paistelefono = 'Bhutan';
UPDATE sense.codigotelefono SET paistelefono = 'Afganistán' WHERE codigotelefono = '+93' AND paistelefono = 'Afghanistan';
UPDATE sense.codigotelefono SET paistelefono = 'Irán' WHERE codigotelefono = '+98' AND paistelefono = 'Iran';
UPDATE sense.codigotelefono SET paistelefono = 'Irak' WHERE codigotelefono = '+964' AND paistelefono = 'Iraq';
UPDATE sense.codigotelefono SET paistelefono = 'Israel' WHERE codigotelefono = '+972' AND paistelefono = 'Israel';
UPDATE sense.codigotelefono SET paistelefono = 'Palestina' WHERE codigotelefono = '+970' AND paistelefono = 'Palestinian Territory';
UPDATE sense.codigotelefono SET paistelefono = 'Jordania' WHERE codigotelefono = '+962' AND paistelefono = 'Jordan';
UPDATE sense.codigotelefono SET paistelefono = 'Líbano' WHERE codigotelefono = '+961' AND paistelefono = 'Lebanon';
UPDATE sense.codigotelefono SET paistelefono = 'Siria' WHERE codigotelefono = '+963' AND paistelefono = 'Syria';
UPDATE sense.codigotelefono SET paistelefono = 'Turquía' WHERE codigotelefono = '+90' AND paistelefono = 'Turkey';
UPDATE sense.codigotelefono SET paistelefono = 'Arabia Saudí' WHERE codigotelefono = '+966' AND paistelefono = 'Saudi Arabia';
UPDATE sense.codigotelefono SET paistelefono = 'Emiratos Árabes Unidos' WHERE codigotelefono = '+971' AND paistelefono = 'United Arab Emirates';
UPDATE sense.codigotelefono SET paistelefono = 'Kuwait' WHERE codigotelefono = '+965' AND paistelefono = 'Kuwait';
UPDATE sense.codigotelefono SET paistelefono = 'Catar' WHERE codigotelefono = '+974' AND paistelefono = 'Qatar';
UPDATE sense.codigotelefono SET paistelefono = 'Baréin' WHERE codigotelefono = '+973' AND paistelefono = 'Bahrain';
UPDATE sense.codigotelefono SET paistelefono = 'Omán' WHERE codigotelefono = '+968' AND paistelefono = 'Oman';
UPDATE sense.codigotelefono SET paistelefono = 'Yemen' WHERE codigotelefono = '+967' AND paistelefono = 'Yemen';
UPDATE sense.codigotelefono SET paistelefono = 'Mongolia' WHERE codigotelefono = '+976' AND paistelefono = 'Mongolia';
UPDATE sense.codigotelefono SET paistelefono = 'Taiwán' WHERE codigotelefono = '+886' AND paistelefono = 'Taiwan';
UPDATE sense.codigotelefono SET paistelefono = 'Hong Kong' WHERE codigotelefono = '+852' AND paistelefono = 'Hong Kong';
UPDATE sense.codigotelefono SET paistelefono = 'Macao' WHERE codigotelefono = '+853' AND paistelefono = 'Macao';
UPDATE sense.codigotelefono SET paistelefono = 'Brunéi' WHERE codigotelefono = '+673' AND paistelefono = 'Brunei';

-- Países de África
UPDATE sense.codigotelefono SET paistelefono = 'Sudáfrica' WHERE codigotelefono = '+27' AND paistelefono = 'South Africa';
UPDATE sense.codigotelefono SET paistelefono = 'Egipto' WHERE codigotelefono = '+20' AND paistelefono = 'Egypt';
UPDATE sense.codigotelefono SET paistelefono = 'Nigeria' WHERE codigotelefono = '+234' AND paistelefono = 'Nigeria';
UPDATE sense.codigotelefono SET paistelefono = 'Kenia' WHERE codigotelefono = '+254' AND paistelefono = 'Kenya';
UPDATE sense.codigotelefono SET paistelefono = 'Marruecos' WHERE codigotelefono = '+212' AND paistelefono = 'Morocco';
UPDATE sense.codigotelefono SET paistelefono = 'Argelia' WHERE codigotelefono = '+213' AND paistelefono = 'Algeria';
UPDATE sense.codigotelefono SET paistelefono = 'Túnez' WHERE codigotelefono = '+216' AND paistelefono = 'Tunisia';
UPDATE sense.codigotelefono SET paistelefono = 'Libia' WHERE codigotelefono = '+218' AND paistelefono = 'Libya';
UPDATE sense.codigotelefono SET paistelefono = 'Etiopía' WHERE codigotelefono = '+251' AND paistelefono = 'Ethiopia';
UPDATE sense.codigotelefono SET paistelefono = 'Ghana' WHERE codigotelefono = '+233' AND paistelefono = 'Ghana';
UPDATE sense.codigotelefono SET paistelefono = 'Sudán' WHERE codigotelefono = '+249' AND paistelefono = 'Sudan';
UPDATE sense.codigotelefono SET paistelefono = 'Sudán del Sur' WHERE codigotelefono = '+211' AND paistelefono = 'South Sudan';
UPDATE sense.codigotelefono SET paistelefono = 'Uganda' WHERE codigotelefono = '+256' AND paistelefono = 'Uganda';
UPDATE sense.codigotelefono SET paistelefono = 'Tanzania' WHERE codigotelefono = '+255' AND paistelefono = 'Tanzania';
UPDATE sense.codigotelefono SET paistelefono = 'Ruanda' WHERE codigotelefono = '+250' AND paistelefono = 'Rwanda';
UPDATE sense.codigotelefono SET paistelefono = 'Burundi' WHERE codigotelefono = '+257' AND paistelefono = 'Burundi';
UPDATE sense.codigotelefono SET paistelefono = 'República Democrática del Congo' WHERE codigotelefono = '+243' AND paistelefono = 'Democratic Republic of the Congo';
UPDATE sense.codigotelefono SET paistelefono = 'República del Congo' WHERE codigotelefono = '+242' AND paistelefono = 'Republic of the Congo';
UPDATE sense.codigotelefono SET paistelefono = 'República Centroafricana' WHERE codigotelefono = '+236' AND paistelefono = 'Central African Republic';
UPDATE sense.codigotelefono SET paistelefono = 'Chad' WHERE codigotelefono = '+235' AND paistelefono = 'Chad';
UPDATE sense.codigotelefono SET paistelefono = 'Camerún' WHERE codigotelefono = '+237' AND paistelefono = 'Cameroon';
UPDATE sense.codigotelefono SET paistelefono = 'Gabón' WHERE codigotelefono = '+241' AND paistelefono = 'Gabon';
UPDATE sense.codigotelefono SET paistelefono = 'Guinea Ecuatorial' WHERE codigotelefono = '+240' AND paistelefono = 'Equatorial Guinea';
UPDATE sense.codigotelefono SET paistelefono = 'Santo Tomé y Príncipe' WHERE codigotelefono = '+239' AND paistelefono = 'Sao Tome and Principe';
UPDATE sense.codigotelefono SET paistelefono = 'Angola' WHERE codigotelefono = '+244' AND paistelefono = 'Angola';
UPDATE sense.codigotelefono SET paistelefono = 'Zambia' WHERE codigotelefono = '+260' AND paistelefono = 'Zambia';
UPDATE sense.codigotelefono SET paistelefono = 'Zimbabue' WHERE codigotelefono = '+263' AND paistelefono = 'Zimbabwe';
UPDATE sense.codigotelefono SET paistelefono = 'Botsuana' WHERE codigotelefono = '+267' AND paistelefono = 'Botswana';
UPDATE sense.codigotelefono SET paistelefono = 'Namibia' WHERE codigotelefono = '+264' AND paistelefono = 'Namibia';
UPDATE sense.codigotelefono SET paistelefono = 'Lesoto' WHERE codigotelefono = '+266' AND paistelefono = 'Lesotho';
UPDATE sense.codigotelefono SET paistelefono = 'Suazilandia' WHERE codigotelefono = '+268' AND paistelefono = 'Swaziland';
UPDATE sense.codigotelefono SET paistelefono = 'Madagascar' WHERE codigotelefono = '+261' AND paistelefono = 'Madagascar';
UPDATE sense.codigotelefono SET paistelefono = 'Mauricio' WHERE codigotelefono = '+230' AND paistelefono = 'Mauritius';
UPDATE sense.codigotelefono SET paistelefono = 'Seychelles' WHERE codigotelefono = '+248' AND paistelefono = 'Seychelles';
UPDATE sense.codigotelefono SET paistelefono = 'Comoras' WHERE codigotelefono = '+269' AND paistelefono = 'Comoros';
UPDATE sense.codigotelefono SET paistelefono = 'Malaui' WHERE codigotelefono = '+265' AND paistelefono = 'Malawi';
UPDATE sense.codigotelefono SET paistelefono = 'Mozambique' WHERE codigotelefono = '+258' AND paistelefono = 'Mozambique';
UPDATE sense.codigotelefono SET paistelefono = 'Malí' WHERE codigotelefono = '+223' AND paistelefono = 'Mali';
UPDATE sense.codigotelefono SET paistelefono = 'Burkina Faso' WHERE codigotelefono = '+226' AND paistelefono = 'Burkina Faso';
UPDATE sense.codigotelefono SET paistelefono = 'Níger' WHERE codigotelefono = '+227' AND paistelefono = 'Niger';
UPDATE sense.codigotelefono SET paistelefono = 'Senegal' WHERE codigotelefono = '+221' AND paistelefono = 'Senegal';
UPDATE sense.codigotelefono SET paistelefono = 'Mauritania' WHERE codigotelefono = '+222' AND paistelefono = 'Mauritania';
UPDATE sense.codigotelefono SET paistelefono = 'Gambia' WHERE codigotelefono = '+220' AND paistelefono = 'Gambia';
UPDATE sense.codigotelefono SET paistelefono = 'Guinea-Bisáu' WHERE codigotelefono = '+245' AND paistelefono = 'Guinea-Bissau';
UPDATE sense.codigotelefono SET paistelefono = 'Guinea' WHERE codigotelefono = '+224' AND paistelefono = 'Guinea';
UPDATE sense.codigotelefono SET paistelefono = 'Sierra Leona' WHERE codigotelefono = '+232' AND paistelefono = 'Sierra Leone';
UPDATE sense.codigotelefono SET paistelefono = 'Liberia' WHERE codigotelefono = '+231' AND paistelefono = 'Liberia';
UPDATE sense.codigotelefono SET paistelefono = 'Costa de Marfil' WHERE codigotelefono = '+225' AND paistelefono = 'Ivory Coast';
UPDATE sense.codigotelefono SET paistelefono = 'Togo' WHERE codigotelefono = '+228' AND paistelefono = 'Togo';
UPDATE sense.codigotelefono SET paistelefono = 'Benín' WHERE codigotelefono = '+229' AND paistelefono = 'Benin';
UPDATE sense.codigotelefono SET paistelefono = 'Eritrea' WHERE codigotelefono = '+291' AND paistelefono = 'Eritrea';
UPDATE sense.codigotelefono SET paistelefono = 'Yibuti' WHERE codigotelefono = '+253' AND paistelefono = 'Djibouti';
UPDATE sense.codigotelefono SET paistelefono = 'Somalia' WHERE codigotelefono = '+252' AND paistelefono = 'Somalia';

-- Países de Oceanía
UPDATE sense.codigotelefono SET paistelefono = 'Australia' WHERE codigotelefono = '+61' AND paistelefono = 'Australia';
UPDATE sense.codigotelefono SET paistelefono = 'Nueva Zelanda' WHERE codigotelefono = '+64' AND paistelefono = 'New Zealand';
UPDATE sense.codigotelefono SET paistelefono = 'Fiyi' WHERE codigotelefono = '+679' AND paistelefono = 'Fiji';
UPDATE sense.codigotelefono SET paistelefono = 'Papúa Nueva Guinea' WHERE codigotelefono = '+675' AND paistelefono = 'Papua New Guinea';
UPDATE sense.codigotelefono SET paistelefono = 'Samoa' WHERE codigotelefono = '+685' AND paistelefono = 'Samoa';
UPDATE sense.codigotelefono SET paistelefono = 'Tonga' WHERE codigotelefono = '+676' AND paistelefono = 'Tonga';
UPDATE sense.codigotelefono SET paistelefono = 'Vanuatu' WHERE codigotelefono = '+678' AND paistelefono = 'Vanuatu';
UPDATE sense.codigotelefono SET paistelefono = 'Islas Salomón' WHERE codigotelefono = '+677' AND paistelefono = 'Solomon Islands';
UPDATE sense.codigotelefono SET paistelefono = 'Kiribati' WHERE codigotelefono = '+686' AND paistelefono = 'Kiribati';
UPDATE sense.codigotelefono SET paistelefono = 'Tuvalu' WHERE codigotelefono = '+688' AND paistelefono = 'Tuvalu';
UPDATE sense.codigotelefono SET paistelefono = 'Nauru' WHERE codigotelefono = '+674' AND paistelefono = 'Nauru';
UPDATE sense.codigotelefono SET paistelefono = 'Islas Marshall' WHERE codigotelefono = '+692' AND paistelefono = 'Marshall Islands';
UPDATE sense.codigotelefono SET paistelefono = 'Micronesia' WHERE codigotelefono = '+691' AND paistelefono = 'Micronesia';
UPDATE sense.codigotelefono SET paistelefono = 'Palaos' WHERE codigotelefono = '+680' AND paistelefono = 'Palau';
UPDATE sense.codigotelefono SET paistelefono = 'Islas Cook' WHERE codigotelefono = '+682' AND paistelefono = 'Cook Islands';
UPDATE sense.codigotelefono SET paistelefono = 'Niue' WHERE codigotelefono = '+683' AND paistelefono = 'Niue';
UPDATE sense.codigotelefono SET paistelefono = 'Tokelau' WHERE codigotelefono = '+690' AND paistelefono = 'Tokelau';
UPDATE sense.codigotelefono SET paistelefono = 'Wallis y Futuna' WHERE codigotelefono = '+681' AND paistelefono = 'Wallis and Futuna';
UPDATE sense.codigotelefono SET paistelefono = 'Nueva Caledonia' WHERE codigotelefono = '+687' AND paistelefono = 'New Caledonia';
UPDATE sense.codigotelefono SET paistelefono = 'Polinesia Francesa' WHERE codigotelefono = '+689' AND paistelefono = 'French Polynesia';
UPDATE sense.codigotelefono SET paistelefono = 'Guam' WHERE codigotelefono = '+1 671' AND paistelefono = 'Guam';
UPDATE sense.codigotelefono SET paistelefono = 'Islas Marianas del Norte' WHERE codigotelefono = '+1 670' AND paistelefono = 'Northern Mariana Islands';
UPDATE sense.codigotelefono SET paistelefono = 'Samoa Americana' WHERE codigotelefono = '+1 684' AND paistelefono = 'American Samoa';
UPDATE sense.codigotelefono SET paistelefono = 'Islas Pitcairn' WHERE codigotelefono = '+870' AND paistelefono = 'Pitcairn';

-- Verificar los cambios más importantes
SELECT codigotelefonoid, codigotelefono, paistelefono 
FROM sense.codigotelefono 
WHERE codigotelefono IN ('+51', '+52', '+57', '+58', '+54', '+56', '+593', '+591', '+595', '+598', '+55', '+502', '+53', '+509', '+1 809', '+504', '+505', '+503', '+506', '+507', '+34', '+33', '+49', '+39', '+44', '+351', '+31', '+32', '+41', '+43', '+1', '+86', '+81', '+82', '+91', '+66', '+65', '+60', '+63', '+62', '+84', '+27', '+20', '+234', '+254', '+212', '+213', '+216', '+218', '+251', '+233', '+61', '+64', '+679', '+675', '+685', '+676', '+678', '+677', '+686', '+688')
ORDER BY codigotelefonoid;
